### ISSUE TITLE
any paper link?

### ISSUE THREAD

**Issue by jinfagang** [zju3dv/snake#1]
any paper link or code info before it release?

**Comment by madebyollin** [comment]
The paper is https://arxiv.org/pdf/2001.01629v1.pdf

**Comment by pengsida** [comment]
I have added the paper link in the readme.

**Comment by jinfagang** [comment]
thanks, does there any schedules for code release, can't wait to see this impressive results?

**Comment by pengsida** [comment]
We will release both the training and test code of the full pipeline if the paper is accepted.
