### ISSUE TITLE
During the train，I meet a problem！

### ISSUE THREAD

**Issue by MachineSzy** [zju3dv/snake#100]
eta: 0:00:02  epoch: 1  step: 371  act_loss: 1.9915  awh_loss: 8.3727  cp_loss: 1.6951  cp_wh_loss: 6.7249  loss: 5.1963  data: 0.9913  batch: 1.9146  lr: 0.000050  max_mem: 9466
eta: 0:07:56  epoch: 2  step: 392  act_loss: 1.9615  awh_loss: 7.6329  cp_loss: 1.6640  cp_wh_loss: 6.4654  loss: 5.0353  data: 2.8531  batch: 4.6566  lr: 0.000050  max_mem: 9466
eta: 0:06:55  epoch: 2  step: 412  act_loss: 1.9884  awh_loss: 7.9758  cp_loss: 1.6627  cp_wh_loss: 6.8305  loss: 5.1318  data: 0.6298  batch: 2.3815  lr: 0.000050  max_mem: 9466
eta: 0:05:54  epoch: 2  step: 432  act_loss: 1.9456  awh_loss: 7.7193  cp_loss: 1.6739  cp_wh_loss: 6.8262  loss: 5.0741  data: 0.2735  batch: 2.0417  lr: 0.000050  max_mem: 9466
eta: 0:04:56  epoch: 2  step: 452  act_loss: 1.9103  awh_loss: 7.0133  cp_loss: 1.6550  cp_wh_loss: 6.6703  loss: 4.9337  data: 0.8286  batch: 2.5557  lr: 0.000050  max_mem: 9466
/pytorch/aten/src/THC/THCTensorScatterGather.cu:100: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 3]: block: [0,0,0], thread: [396,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/pytorch/aten/src/THC/THCTensorScatterGather.cu:100: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 3]: block: [0,0,0], thread: [397,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 50, in main
    train(cfg, network)
  File "train_net.py", line 25, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/content/snake/lib/train/trainers/trainer.py", line 38, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/ct_rcnn.py", line 38, in forward
    cp_wh_loss = self.cp_wh_crit(output['cp_wh'], cp_wh, cp_ind, cp_01)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/snake/lib/utils/net_utils.py", line 245, in forward
    loss = self.loss(output * weight, target * weight, reduction='sum')
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f744d540441 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f744d53fd7a in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x13652 (0x7f744b3b6652 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x50 (0x7f744d530ce0 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x30facb (0x7f744bd52acb in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x1420bb (0x7f748c8510bb in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3c30f4 (0x7f748cad20f4 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x3c3141 (0x7f748cad2141 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #8: python3() [0x54f226]
frame #9: python3() [0x572cd0]
frame #10: python3() [0x54ef2b]
frame #11: python3() [0x54ef2b]
frame #12: python3() [0x588a98]
frame #13: python3() [0x5ad558]
frame #14: python3() [0x5ad56e]
frame #15: python3() [0x5ad56e]
frame #16: python3() [0x5ad56e]
frame #17: python3() [0x5ad56e]
frame #18: python3() [0x5ad56e]
frame #19: python3() [0x56b636]
<omitting python frames>
frame #25: __libc_start_main + 0xe7 (0x7f74979bfb97 in /lib/x86_64-linux-gnu/libc.so.6)

why it happens？what should I do？

**Comment by pengsida** [comment]
There are some bugs in your data.
