### ISSUE TITLE
Question about the relationship between Deep Snake and Snake Algorithm

### ISSUE THREAD

**Issue by tommy-qichang** [zju3dv/snake#103]
Hi,
It's great to see the code and the cvpr paper. Great job!
I have one question. In your paper, you mentioned deep snake implements the classic idea of snake algorithms with a learning-based approach. But I think the snake algorithm is unsupervised. And in the typical settings, the snake algorithm should find any object given the initial contour and inner, outer energy. But it seems deep snake is supervised, and deeply rely on the training data. What I wanna do is to apply deep snake exactly like snake algorithm: draw a contour, and find the nearest ROIs. I think maybe current deep snake is not for such purpose, right?

**Comment by pengsida** [comment]
All learning-based algorithms need be supervised with training data.
After training, deep snake can do what you want, namely segmenting the object within the provided contour.

**Comment by tommy-qichang** [comment]
Isn't the unsupervised ,semi-supervised learning, one-short segmentation a learning-based algorithms?
The initial contour already give the rough information of the ROI, so I expect the deep snake would learn to find the contours of all kinds rather than the contour of a specific label.

**Comment by tommy-qichang** [comment]
Got it. 
I'll try to apply the deep snake for our current problem. Thanks again.
