### ISSUE TITLE
coco dataset training

### ISSUE THREAD

**Issue by hyunas1996** [zju3dv/snake#107]
Thanks for nice code!

I have a question. Is this model pre-trained with coco dataset?
Your answer will be really helpful to my plan. Thanks a lot :-)

**Comment by pengsida** [comment]
No, I do not provide the model trained on COCO.
I used to train the network on COCO, but I cannot find the trained model and the corresponding code.

**Comment by hyunas1996** [comment]
Oh thanks for answering!

Then I thinks I need to retrain the model by myself :-)

If you don't mind, would you please explain the training description in your wiki?
Is that means how to fine-training the model?

Thanks a lot!!!

**Comment by pengsida** [comment]
It is important to follow the code of CenterNet.
I find that I must use the exactly code to obtain the performance on COCO reported by CenterNet.
You could load the pre-trained model of CenterNet.
Then fine-tune the network.

**Comment by hyunas1996** [comment]
Alright! Thanks for your kindness.
I will try and then if I success or need help again, then I will mention again :-)
Thanks a lot~
