### ISSUE TITLE
报错：FileNotFoundError: [Errno 2] No such file or directory: 'data/cityscapes/coco_ann/instance_val.json'

### ISSUE THREAD

**Issue by HanazawaKanana** [zju3dv/snake#108]
FileNotFoundError: [Errno 2] No such file or directory: 'data/cityscapes/coco_ann/instance_val.json'
请问这个文件在什么地方，我看cityscapes数据集内没这个文件

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/97452835-1c7e4180-1970-11eb-8a44-1e9b2e059b9f.png)
