### ISSUE TITLE
Something error occur when evaluate the each class

### ISSUE THREAD

**Issue by Yooyi0401** [zju3dv/snake#110]
![image](https://user-images.githubusercontent.com/49556328/98496266-370fbf00-227c-11eb-87b6-4de2f0b2bcd9.png)
上述config是使用sbd格式进行训练后结果，但想评估各个class 的mAP时发生错误
我在训练时有将categories  filter少部份类别，想请问该如何修改它？

**Comment by pengsida** [comment]
你怎么filter类别的

**Comment by pengsida** [comment]
可能是修改这里的代码：https://github.com/zju3dv/snake/blob/master/lib/evaluators/sbd/snake.py#L31

**Comment by Yooyi0401** [comment]
> 你怎么filter类别的

因為我只需要车辆相关的类，自定义类别就可以filter其余类别了

> 可能是修改这里的代码：https://github.com/zju3dv/snake/blob/master/lib/evaluators/sbd/snake.py#L31

好的感谢你我会在试试看进行修改
