### ISSUE TITLE
error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by TinyMonsterLee** [zju3dv/snake#111]
您好，非常感谢您的代码分享。当我在运行‘’’python setup.py install --cuda_ext --cpp_ext‘’’这一步时首先报错说我的gcc版本过高，当我使用‘’’sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100‘’’将gcc版本切换至gcc-6再运行代码‘’’python setup.py install --cuda_ext --cpp_ext‘‘’，遇到了‘’’error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1‘’’。
我的pytorch版本是1.1.0，cuda是9.0。

**Comment by pengsida** [comment]
建议列出完整的报错信息。

**Comment by TinyMonsterLee** [comment]
感谢您的回复，我通过安装cuda10解决了这个问题
