### ISSUE TITLE
Request detection AP on cityscapes val set

### ISSUE THREAD

**Issue by NareshGuru77** [zju3dv/snake#112]
Could you share the detection AP (overall and per class) on the cityscapes val dataset. This results would be very helpful to compare against. 

Thank you.

**Comment by pengsida** [comment]
You can run the released code to obtain the per class mask AP.
Cityscapes does not provide the api to evaluate the detection performance.

**Comment by NareshGuru77** [comment]
1. maybe, is detection AP measured using coco API available ?
2. If in case mask AP for cityscapes was also measured with coco API, were there any differences in results between the mask AP calculated by coco API and cityscapes API ?

Thank you.

**Comment by pengsida** [comment]
@NareshGuru77 
1. Yes, I provide the detection AP using coco API.
2. The mask AP calculated by coco API is lower than cityscapes API.

**Comment by NareshGuru77** [comment]
@pengsida 

Thank you. Could you provide values on any of the datasets preferably cityscapes on the difference between the mask AP of coco and cityscapes API ?

**Comment by pengsida** [comment]
I do not have the environment to run the code.

https://github.com/zju3dv/snake#testing-on-cityscapes
![image](https://user-images.githubusercontent.com/11582122/100351186-02df2100-3026-11eb-9af7-b03ce6b07f53.png)

**Comment by NareshGuru77** [comment]
Coco bbox AP for cityscapes:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.411
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.669
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.419
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.161
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.394
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.611
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.273
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.477
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.511
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.280
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.504
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.708

Coco Mask AP for cityscapes dataset:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.368
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.629
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.343
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.106
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.327
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.583
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.261
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.428
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.453
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.248
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.425
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.658

Cityscapes API mask AP for cityscapes dataset is 37.4 which is 0.6 % higher than using coco API.
