### ISSUE TITLE
伟大的作者大人

### ISSUE THREAD

**Issue by monarchdemon** [zju3dv/snake#114]
伟大的作者大人你好，我是一个小白，我想在Windows上实现您的这个项目，但是弄了很久还是不得入门。
目前的我问题就是：您的项目对于我这个小白来说相当的庞大，小的可以说无法看懂这个项目，我的主要目的是想要实现deep snake的轮廓提取，并且想试着做一些简单的调试，但是，我高了很久还是无从下手，所以我厚着脸皮向您求助一下，希望您觉得我这个小白还可以抢救一下，给点儿帮助，感激不尽！

**Comment by pengsida** [comment]
建议提具体的问题。

**Comment by monarchdemon** [comment]
具体的就是，我想要一个在您项目中筛选出完整的deep snake算法，能进行修改的那种，就是不需要您这么庞大的项目，能用deepsnake跑出轮廓就行

**Comment by pengsida** [comment]
你可以跟踪demo的代码看看：https://github.com/zju3dv/snake#demo

**Comment by monarchdemon** [comment]
您这个我看了，项目庞大，看了好久，没咋弄明白，不过谢谢您的耐心回复和帮助了，我在努力努力

**Comment by monarchdemon** [comment]
冒昧且厚颜无耻的问您一下，你那边有比较详细的关于snake和deep snake方面的参考文献吗？如果可以分享的话，不行的话您就当没有看到我的无理要求哈。非常感谢您的耐心回复
