### ISSUE TITLE
Questions FPS calculations

### ISSUE THREAD

**Issue by NareshGuru77** [zju3dv/snake#115]
1. Could you point to or provide the code used to calculate the FPS values mentioned in the paper ? 

2. Also, for cityscapes fps values such as 4.6, 2.2 and so on are reported. Are these values measured in a different device or using a different procedure ?

Thank you.

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/100871578-76c47200-34db-11eb-9a7c-02096f0b7f0c.png)

The timing results of other methods were obtained from "Instance segmentation by jointly optimizing spatial embeddings and clustering bandwidth."

**Comment by NareshGuru77** [comment]
Thank you. I checked this and it gives me around 5 fps close to the value reported in the paper. 

Could you also point to the code which provides fps such as 32.3 fps on SBD dataset as reported in the paper ? Is this code similar to any benchmark fps codes provided for example in detectron2 ?

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/100955405-71a20a00-3551-11eb-933f-4d46c7d0ba63.png)
