### ISSUE TITLE
预测输入图像太大，1080*1920，没有检测结果

### ISSUE THREAD

**Issue by xjock** [zju3dv/snake#117]
缩小成540*960有检测结果，这是什么原理？

**Comment by pengsida** [comment]
检测和目标物体scale有关。

**Comment by xjock** [comment]
> 检测和目标物体scale有关。

需要自己缩小图像还是修改模型中的scale参数即可？感谢

**Comment by pengsida** [comment]
可以自己改变图像尺寸。

**Comment by xjock** [comment]
> 可以自己改变图像尺寸。

明白了，感谢您的回复。
