### ISSUE TITLE
Use init['i_it_py'] for training py_pred and  evolve['i_it_py'] for testing py ?

### ISSUE THREAD

**Issue by cccccccccy** [zju3dv/snake#124]
Hello，when reading your source code, I have noticed that you use init['i_it_py'] for training py_pred and  evolve['i_it_py'] for testing py. And in my opinion, init['i_it_py'] is a preprocessed input,  evolve['i_it_py'] is a prediction about init['i_it_py']. Under this thought, deepsnake works well. However, I can't understand why? Could you please tell me about this? Thanks!

**Comment by pengsida** [comment]
There is no difference on performance by training snake with `evolve['i_it_py']`.
