### ISSUE TITLE
训练自己的数据

### ISSUE THREAD

**Issue by wangjin1234567891** [zju3dv/snake#125]
![image](https://user-images.githubusercontent.com/76192707/102582279-37ce2780-413d-11eb-80c1-7f439b2b752e.png)
![image](https://user-images.githubusercontent.com/76192707/102582297-41578f80-413d-11eb-9bd6-1e175d326ca6.png)
我的数据集和标签分别是这样，我该如何通过您这个优秀的模型进行训练呢

**Comment by pengsida** [comment]
你首先需要把mask转成bounding box。
这是一个公开数据集吗

**Comment by wangjin1234567891** [comment]
我使用的是WHU Building Dataset，您能详细说说吗？

**Comment by wangjin1234567891** [comment]
数据集是公开的

**Comment by pengsida** [comment]
我有转换sbd数据集为coco格式的代码：https://github.com/zju3dv/snake/blob/master/tools/convert_sbd.py

**Comment by wangjin1234567891** [comment]
![image_screenshot_26 12 2021](https://user-images.githubusercontent.com/76192707/103144022-24cedf00-475d-11eb-849a-40c3b4bfc1b6.png)
![mask_screenshot_26 12 2020](https://user-images.githubusercontent.com/76192707/103144025-28626600-475d-11eb-8dd0-b8c16c88f705.png)
我生成的coco datatset，只有一个bounding box，但contour是正常的，请问这样会影响训练吗？再次麻烦您。

**Comment by wangjin1234567891** [comment]
已经解决，谢谢

**Comment by renweizou** [comment]
您好，我也想用WHU Building Dataset来训练deepsnake，想请教下您该如何处理WHU Building Dataset数据集，期待您的回复！非常感谢！！！
