### ISSUE TITLE
Some questions about snake

### ISSUE THREAD

**Issue by NeuZhangQiang** [zju3dv/snake#129]
看到提问贴中有人用中文提问，为了更准确的表达我的意思，这里我也用中文提问了，请见谅。

1. 为什么要做一步从Detected box 到Octagon contour？按理来说，有了Detected box后，不就可以启动Deep Snake了嘛？得到octagon contour是为了得到更好的初始轮廓嘛？
我看loss中，你给了一个关于Extreme points的loss。为什么要去训练Extreme points？为什么不用Extremenet用来检测Detected box？这样不就直接给出Extrement points了嘛？

2. 在DeepSnake框架中（如下图），输入只需要Contour？应该是Contour+feature map吧？
![image](https://user-images.githubusercontent.com/62534955/103270580-392c0980-49f3-11eb-8b5c-0a97811922e6.png)

2.1 训练过程中，需不需要对feature map更新？看上面这图的意思，是不需要更新嘛？直接用别的网络来提取feature map？所以整个DeepSnake网络只需要更新一维循环卷积的kernel值？

2.2 Fusion的Max Pooling的输入是N\*C0，我看networks/snake/snake.py里面的过程是：
```
        global_state = torch.max(self.fusion(state), dim=2, keepdim=True)[0]
        global_state = global_state.expand(global_state.size(0), global_state.size(1), state.size(2))
        state = torch.cat([global_state, state], dim=1)
        x = self.prediction(state)
```
为什么要对Fusion的结果取最大？然后一起送给```self.prediction```?为什么不直接把 ```self.fusion(state)``` 送给prediction？

2.3 文中有说，通过几次迭代，来逐渐逼近真实contour。最后的loss是把中间几次迭代的loss加到最后嘛？还是只要最后一次迭代的contour的loss？

3. 关于"Multi-component detection"这一部分，我有点疑惑。我看文章的意思是说：先通过一般的目标检测框架（我看代码里面是用CenterNet，对吧？）检测出汽车的object，然后把这个object的feature map截出来，做一个RoIAlign，然后再接一个detector做不同component的检测，这个接的detector也是centernet嘛？
还有一个问题，由于遮挡的问题，假如一个object断成了三截，如果最开始检测的目标定位框也只包含了两截，那么是不是Deep Snake也只能得到两截的分割结果？

4. deep snake的一个优点是能省显存，计算量小。我本身是做医疗图像的，医疗图像的显存消耗更为明显。但是，就我的理解，deep snake好像没法用到三维图像的分割。可以嘛？

非常期待作者大大的答疑解惑~~~感谢！！！

**Comment by pengsida** [comment]
1. 有了Detected box后，可以启动Deep Snake。得到octagon contour是为了得到更好的初始轮廓。可以用Extremenet用来检测Detected box。
2. 输入是定义在contour上的feature。
2.1 训练过程中需要更新feature map。
2.2 对Fusion的结果取最大，是给各个节点的feature做max pooling。可以把`self.fusion(state)`送给prediction。
2.3 只要最后一次迭代的contour的loss。https://github.com/zju3dv/snake/blob/master/lib/train/trainers/snake.py#L42
3. 这个接的detector也是centernet。
4. deep snake没法用到三维图像的分割。可以看这篇论文：https://arxiv.org/abs/2011.08826

**Comment by NeuZhangQiang** [comment]
@pengsida 非常感谢您的耐心解答，我还有几个问题没弄明白。

1. 为什么Deep Snake 训练的时候，要求一个Extreme points的loss？是出于什么考虑，要这么一个loss?
2.1 为什么要对Fusion的结果取最大？是为了出于显存的考虑嘛？还是什么原因呢？
3. 您论文中贴出来的速度，是单纯Deep snake的速度，还是包含了最开始目标检测定位框的时间？

感谢！

**Comment by pengsida** [comment]
1. Extreme points的loss用来训练extreme points的预测。
2.1 这是fuse node features，用来得到全局的信息。
2. 包括了目标检测定位框的时间。

**Comment by NeuZhangQiang** [comment]
1. 为什么Deep Snake在中间过程中，要训练extreme points？为什么不直接用ExtremeNet的结果就好？
我的理解是：extreme point是为了得到一个较好的初始轮廓，如果是这样的话，只要用ExtremeNet得到极值点，不久可以了？

5. 我还有一个新问题，就是训练过程中，有两个组成，一个是提取feature map的backbone，另一个是Deep Snake的一维卷积部分。这两部分的连接，就是Deep Snake的一维卷积的输入是从feature map来的。我的理解来看，这个连接有点弱。您这边的feature map是用了CenterNet/ExtremeNet的预训练模型。我想问问，这里的预训练模型有什么选择要求吗？比如，一定需要用object detection的模型？我换成分割的Unet行不行？
6. 另外，在训练的过程中，有什么技巧嘛？是先固定CenterNet的参数，先更新一维卷积部分，最后再一起更新嘛？还是说，直接不需要预训练模型，我直接让CenterNet和一维卷积一起训练，这样也行？

**Comment by pengsida** [comment]
1. Deep Snake在中间过程中可以直接用ExtremeNet的结果。
2. 你可以换成分割的Unet试试，我没试过。
3. 我有让CenterNet和一维卷积一起训练，也有分开训，你可以分别看看效果。

**Comment by NeuZhangQiang** [comment]
1. Deep Snake在中间过程中，需要用到ExtremeNet的什么结果？ExtremeNet不就是为了提供一个较好的初始轮廓嘛？

**Comment by pengsida** [comment]
用ExtremeNet得到极值点。

**Comment by NeuZhangQiang** [comment]
ExtremeNet 一开始得到极值点，形成一个初始轮廓，不就好了嘛？这样的话，直接用训练好了的ExtremeNet网络不就行？为什么Deep Snake要去把它的loss也加入训练loss？

**Comment by pengsida** [comment]
1. 你可以用ExtremeNet试试。
2. 我不清楚数据，不确定。如果无法过拟合，应该是有bug，或者learning rate设置有问题。
