### ISSUE TITLE
BUG about yacs.py

### ISSUE THREAD

**Issue by YYYyangyiyao** [zju3dv/snake#130]
您好，我在运行train_net的时候，出现了AttributeError: segm_or_bbox错误，在yacs.py文件中，_FILE_TYPES = (file, io.IOBase)中的file是什么文件，因为没有看到解释这个文件是指什么，我的理解是configs下的yaml文件，不知道理解的对不对？

**Comment by pengsida** [comment]
请给出详细的报错信息。

**Comment by YYYyangyiyao** [comment]
File "F:\segmentationl\lib\config\yacs.py", line 118, in __getattr__
    raise AttributeError(name)
AttributeError: segm_or_bbox

**Comment by pengsida** [comment]
你执行的是哪个命令

**Comment by YYYyangyiyao** [comment]
在pycharm内运行train_net.py，windows下运行的

**Comment by pengsida** [comment]
需要执行完整的命令，pycharm可以设置。
![image](https://user-images.githubusercontent.com/11582122/103335446-e5cbc100-4aaf-11eb-93b1-becb1ac8895e.png)

**Comment by YYYyangyiyao** [comment]
这是训练city数据集的，训练coco数据集没有coco_rcnn_snake.yaml

**Comment by pengsida** [comment]
你可以用`coco_snake.yaml`。
但我没有放在coco上完全一样的训练代码。

**Comment by YYYyangyiyao** [comment]
感谢您的耐心回复，在训练city数据集的时候，出现错误
File "f:\lib\datasets\cityscapes\rcnn_snake.py", line 177, in __getitem__
    height, width = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'
检查了训练数据集的路径，但是还是报这个错误，您知道是什么原因吗

**Comment by pengsida** [comment]
图片路径不对。
