### ISSUE TITLE
A question about train

### ISSUE THREAD

**Issue by YYYyangyiyao** [zju3dv/snake#132]
python train_net.py --cfg_file configs/city_ct_rcnn.yaml model rcnn_det
loading annotations into memory...
Done (t=0.16s)
creating index...
index created!
load model: data/record/snake\ct_rcnn\rcnn_det\9.pth
loading annotations into memory...
Done (t=0.12s)
creating index...
index created!
  0%|                                                                                          | 0/492 [00:00<?, ?it/s]
您好，我在训练的时候，遇到了下载文件失败的情况，请问这是下载什么文件，试了很多次最终都失败了，或者您有没有下载链接。

**Comment by pengsida** [comment]
下载pytorch的预训练模型：https://github.com/zju3dv/snake/blob/master/lib/networks/rcnn_snake/dla.py#L23
