### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by YYYyangyiyao** [zju3dv/snake#133]
下载pytorch的预训练模型：https://github.com/zju3dv/snake/blob/master/lib/networks/rcnn_snake/dla.py#L23
您好，这个预训练模型有什么用？

**Comment by YYYyangyiyao** [comment]
您好，我在下载apex的时候遇到如下问题：
按照官网给出的安装步骤：
$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-v27okrpm/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-v27okrpm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-bcf91tdd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ncuer/.local/include/python3.6m/apex Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-wccep1j2'

nvcc --version 是V10.0.130，torch.version.cuda也是10.0.130，下载的pytorch==1.2.0 torchvision==0.4.0 

请问这是什么问题

**Comment by pengsida** [comment]
下载预训练模型是用来初始化模型参数的。

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/103474531-d74b1580-4ddf-11eb-8da4-29e8aedc9bdf.png)
