### ISSUE TITLE
question

### ISSUE THREAD

**Issue by amandaluof** [zju3dv/snake#135]
I am confused about formular 3-1-1, that the features of contour vertices are defined as a
periodic signal. I don't know why you use Sigma here. I think it should be as shown in pic2
<img width="189" alt="image" src="https://user-images.githubusercontent.com/44992004/103510932-10978a00-4ea1-11eb-835c-4ce675f94c97.png">
<img width="262" alt="image" src="https://user-images.githubusercontent.com/44992004/103511270-acc19100-4ea1-11eb-8538-f162262e701c.png">

**Comment by pengsida** [comment]
https://en.wikipedia.org/wiki/Circular_convolution
