### ISSUE TITLE
unrecognized command line option std=c ++14

### ISSUE THREAD

**Issue by CangHaiQingYue** [zju3dv/snake#136]
您好，我在编译lib下面相关文件的时候报了这个错，我升级gcc和g++到了5.4.0版本，依然报错，这个是什么问题，您知道么。

**Comment by pengsida** [comment]
请给出详细报错信息和相应的命令。

**Comment by CangHaiQingYue** [comment]
> 请给出详细报错信息和相应的命令。

问题已解决  谢谢！
