### ISSUE TITLE
 A question about train

### ISSUE THREAD

**Issue by hhboy98** [zju3dv/snake#138]
您好，lib.csrc.dcn_v2  的__init__.py 是空的，找不到_ext这个方法，请问是我环境的问题还是我代码缺失的问题呢

**Comment by fdiskdc** [comment]
You have not apply as folling, I guess:
"
ROOT=/path/to/snake
cd $ROOT/lib/csrc
export CUDA_HOME="/usr/local/cuda-9.0"
cd dcn_v2
python setup.py build_ext --inplace
cd ../extreme_utils
python setup.py build_ext --inplace
cd ../roi_align_layer
python setup.py build_ext --inplace
"
