### ISSUE TITLE
The results of running the test set during testing and training are not the same.

### ISSUE THREAD

**Issue by cccccccccy** [zju3dv/snake#139]
Thanks for your work. I made changes on your model, but while testing, I encountered the following problems. The results of running the test set during testing and training are not the same. Excuse me, have you encountered similar problems during the experiment. If so, how did you solve it?

**Comment by pengsida** [comment]
Do you mean that the evaluation results during testing and training?
If you are Chinese, you could communicate with me in Chinese.

**Comment by cccccccccy** [comment]
好的彭哥，英语不太标准见笑了，问题是训练与测试时同一张图片的预测结果不一致，我检查了模型参数正确导入了，不知道问题出在哪里，想问下您有没有遇到过这种情况。谢谢！

**Comment by pengsida** [comment]
network.train()和network.eval()，网络表现不一样。

**Comment by cccccccccy** [comment]
那，请问关于Dataset的数据归一化处理在哪个文件中呢？是在lib/datasets/transforms.py中吗？

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/blob/454e062fe46d35dcaeedd22352e82d9ac1688548/lib/utils/snake/snake_coco_utils.py#L57

**Comment by cccccccccy** [comment]
请问，在训练的时候，第二阶段训练时，需要冻结第一阶段训练的det model的参数吗？谢谢！

**Comment by pengsida** [comment]
不需要。
