### ISSUE TITLE
training problems.

### ISSUE THREAD

**Issue by wanglaotou** [zju3dv/snake#14]
i follow the readme, and i run python train_net.py, but i get this error:
![图片](https://user-images.githubusercontent.com/12837585/75537027-35d19580-5a51-11ea-85c8-58f52c5da705.png)
and i don't find train in lib, am i miss something?

**Comment by wanglaotou** [comment]
![图片](https://user-images.githubusercontent.com/12837585/75537205-8ea12e00-5a51-11ea-9f3b-f57cfc8b93c9.png)
![图片](https://user-images.githubusercontent.com/12837585/75537237-9a8cf000-5a51-11ea-9bf5-558ed677ecaf.png)
wish get your reply.

**Comment by pengsida** [comment]
I have not uploaded the complete code yet.
I will finish it tomorrow.

**Comment by pengsida** [comment]
I uploaded all the code.
