### ISSUE TITLE
output['ct_hm'] size didn't match the size of batch['ct_hm']

### ISSUE THREAD

**Issue by hhboy98** [zju3dv/snake#140]
RuntimeError: The size of tensor a (128) must match the size of tensor b (512) at non-singleton dimension 3. 不好意思打扰您了，我想问一下，为什么最后我的网络output['ct_hm']的size是torch.Size([10, 5, 128, 128])

**Comment by pengsida** [comment]
你说 output['ct_hm'] 和 batch['ct_hm'] 的size不一样吗

**Comment by hhboy98** [comment]
对的，他们分别为
output['ct_hm']：torch.Size([10, 5, 128, 128])
 batch['ct_hm']：torch.Size([10, 5, 512, 512])

**Comment by pengsida** [comment]
你改过代码吗

**Comment by hhboy98** [comment]
没有修改networks部分的代码，但是我使用的自己的数据集

**Comment by pengsida** [comment]
你改过数据集的代码吗

**Comment by hhboy98** [comment]
dla网络输入需要将输入图像大小固定为128x128吗？

**Comment by pengsida** [comment]
不需要。

**Comment by hhboy98** [comment]
我懂啦，感谢您的指导~~
