### ISSUE TITLE
DeepSnake算法中的目标检测代码

### ISSUE THREAD

**Issue by www195** [zju3dv/snake#144]
请问如果暂时只想实现目标检测这一过程，DeepSnake算法给出的代码对应的目标检测的代码在什么位置？

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/blob/master/lib/networks/snake/ct_snake.py#L56

**Comment by www195** [comment]
感谢您的答复！
那我该Debug到哪一步呢？

**Comment by pengsida** [comment]
什么意思。

**Comment by www195** [comment]
就是目前我们只需要完成目标检测这一步，希望处理后的图片中只出现目标框，该怎样操作，代码需要运行到哪一步？

**Comment by pengsida** [comment]
这一步：https://github.com/zju3dv/snake/blob/master/lib/networks/snake/ct_snake.py#L56
