### ISSUE TITLE
代码能不能加个注释啊，帮助我们更好地理解经典

### ISSUE THREAD

**Issue by Sand0001** [zju3dv/snake#145]
好难啊，代码通篇没有一点注释，作者大大要不要普照一下人间~
感谢

**Comment by pengsida** [comment]
注释的工作量很大。

**Comment by Sand0001** [comment]
随便注释一下就可以啦，比如config文件中的变量含义，核心函数的功能，一点也没有只能靠去猜了，小白做不到和大神的心有灵犀啊（暴风哭泣~~撒泼打滚~~）

**Comment by pengsida** [comment]
哪有看不懂可以在这里问。

**Comment by Sand0001** [comment]
![image](https://user-images.githubusercontent.com/45196750/108689529-26860a80-7534-11eb-86ca-059ec7929f24.png)

**Comment by Sand0001** [comment]
可以帮忙解释下output里面这几个key的含义吗

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/blob/master/lib/datasets/cityscapes/rcnn_snake.py#L235
