### ISSUE TITLE
Train on COCO

### ISSUE THREAD

**Issue by pixelsmaker** [zju3dv/snake#146]
Did you train snake on COCO by training the detector and snake module together like SBD? or the way on Cityscapes?

**Comment by pixelsmaker** [comment]
and get the 30.3 mAP on COCO test-dev using the backbone DLA34+DCNv2?

**Comment by pengsida** [comment]
The way on Cityscapes.
I recommend you to use DANCE: https://openaccess.thecvf.com/content/WACV2021/papers/Liu_DANCE_A_Deep_Attentive_Contour_Model_for_Efficient_Instance_Segmentation_WACV_2021_paper.pdf
