### ISSUE TITLE
有关demo的问题

### ISSUE THREAD

**Issue by caiyancheng** [zju3dv/snake#147]
您好，我在跑demo程序的时候，好像展示的图像并没有检测边框，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/70524893/109017367-10be4400-76f2-11eb-8b3a-28f21ec7f516.png)

**Comment by caiyancheng** [comment]
@pengsida

**Comment by pengsida** [comment]
抱歉，我看到忘回了。
看起来是没加载预训练模型。

**Comment by caiyancheng** [comment]
是那个197.pth是吗？

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/109276928-986e9480-7851-11eb-8446-0eb7409af9fe.png)

**Comment by caiyancheng** [comment]
谢谢，我的问题已经解决

**Comment by caiyancheng** [comment]
还有一个问题是，请问ct_score是什么意思？

**Comment by pengsida** [comment]
检测分数的threshold。
