### ISSUE TITLE
一些关于代码的小问题

### ISSUE THREAD

**Issue by caiyancheng** [zju3dv/snake#148]
您好，我对于代码有一些小问题：
1、此代码屡次出现rcnn字眼，但是paper中确未曾提起，请问这个模型与rcnn有何关系？
2、下面三行分别代表什么含义
![image](https://user-images.githubusercontent.com/70524893/109420031-4a04f580-7a0b-11eb-86b2-0a88da25e197.png)

**Comment by pengsida** [comment]
1. 和rcnn没有关系。取这个变量名是因为先检测bbox，再做multi-component detection，所以叫rcnn。
2. 这个和算法没什么关系。

**Comment by caiyancheng** [comment]
请问long_rcnn_det这个文件夹原本是用来做什么的呢？

**Comment by caiyancheng** [comment]
请问如果我想要在cityscape中只对道路进行分割，对人进行bbox检测（其它类别忽略），我应该在代码的哪些部分改哪些内容呢？

**Comment by pengsida** [comment]
你说的long_rcnn_det文件夹在哪

**Comment by pengsida** [comment]
你说用预训练模型还是自己训练

**Comment by caiyancheng** [comment]
1、long_rcnn_det在代码中被提及，在此处（鼠标所指的位置）：
![image](https://user-images.githubusercontent.com/70524893/109493520-97469d00-7ac7-11eb-854c-c089555051aa.png)

2、二者都可以，我希望可以借此提高test时的FPS（即只对道路进行完整的分割，而对人只进行到Centernet检测，其他类别不进行操作），并且最后需要计算道路和人的bbox的重叠面积，您有什么好的建议吗？

**Comment by pengsida** [comment]
1. long_rcnn_det是放detection预训练模型的文件夹。
2. 这份代码没有对道路进行分割。你可以训练一个只检测人的CenterNet，训练一个道路的semantic segmentation。

**Comment by caiyancheng** [comment]
那如果我想基于此代码，加入对道路的分割，我应该在哪里加呢？

**Comment by pengsida** [comment]
这个算法做道路分割，我觉得效果不好。不知道你想分割怎样的道路。

**Comment by caiyancheng** [comment]
好的，谢谢

**Comment by caiyancheng** [comment]
我就是想按照cityscape中的标注分割道路，请问如果我想让这个代码中的Center部分对道路也进行检测，我应该如何更改代码呢？

**Comment by caiyancheng** [comment]
我说的道路就是如下图所示的暗紫色部分
![image](https://user-images.githubusercontent.com/70524893/109652665-0c36d700-7b9b-11eb-9132-3ccd20f1c4f2.png)

**Comment by pengsida** [comment]
Contour-based methods不适合做这样的分割。

**Comment by caiyancheng** [comment]
请问原因是什么呢？

**Comment by caiyancheng** [comment]
尽管如此，我还是想要尝试一下（我正好想看看这种方法会分割出什么样的道路），请问您能给一点指点吗？
1、我想让这个代码中的Centernet部分对道路也进行检测，我应该如何更改代码呢
2、如果我想这个让他对道路也进行分割，我应该如何更改呢？
谢谢您的指导

**Comment by pengsida** [comment]
道路的轮廓很复杂。

**Comment by pengsida** [comment]
你需要生成道路的annotation。然后改yaml文件里ct_hm为想检测的类别的数量。
yaml文件：https://github.com/zju3dv/snake/blob/master/configs/city_rcnn_snake.yaml#L22

**Comment by caiyancheng** [comment]
非常感谢
