### ISSUE TITLE
Text Detection using SNAKE

### ISSUE THREAD

**Issue by deepseek** [zju3dv/snake#15]
@pengsida 
Hi there,

it would be very interesting testing the benefits of SNAKE in text detection.
Have you ever considered that.

**Comment by pengsida** [comment]
Yes, snake is a good representation for text.
But I am not familiar with the concrete setting of text detection, so I have not performed the relevant experiments.

**Comment by deepseek** [comment]
text detection is very similar to object detection. with some preprocessing differences perhaps.
think about it, and keep thinking about it

**Comment by honghande** [comment]
@deepseek 你好，请问你说的文本检测预处理与对象的差异在哪里，期待交流247607771我微信
