### ISSUE TITLE
关于标注

### ISSUE THREAD

**Issue by caiyancheng** [zju3dv/snake#150]
您好，我想问一下，以下两个标注，在cityscape的训练中你是只用了coco_ann吗？
![image](https://user-images.githubusercontent.com/70524893/109777367-9a17ce00-7c3e-11eb-9767-e08fa855e904.png)

**Comment by caiyancheng** [comment]
包括请问您有写标注的代码吗？就是将cityscape的标注格式改为coco的

**Comment by caiyancheng** [comment]
![image](https://user-images.githubusercontent.com/70524893/109819333-ea0e8900-7c6e-11eb-93a5-ee7b60b879f2.png)
请问您的这些数据是从哪里得到的呢？

**Comment by pengsida** [comment]
我忘了，可能是从curve gcn代码里看到的。

**Comment by caiyancheng** [comment]
请问这个Num_class在程序中的作用是什么呢？

**Comment by pengsida** [comment]
我记得没有用到。

**Comment by caiyancheng** [comment]
谢谢您的回复，我还想问一下，如果cityscape用cityscape格式的val，会比用coco格式标注慢很多吗？
因为您的coco格式中并未标出road

**Comment by pengsida** [comment]
会慢很多。

**Comment by caiyancheng** [comment]
您真的找不到那个将cityscape转成coco格式的代码了吗？/（*……*）/
我在网上也找不到好的代码
如果作者大大有时间，能麻烦您找一下吗？

**Comment by pengsida** [comment]
我找不到。
