### ISSUE TITLE
What different between CityscapesVal and CityscapesCocoVal ?

### ISSUE THREAD

**Issue by nightfuryyy** [zju3dv/snake#155]
Thank you so much for awesome repo. 
I tried train snake model on cityscapes dataset with only 5 class.
I find 2 type of validate dataset.
So what different between CityscapesVal and CityscapesCocoVal ?
Thank you so much.

**Comment by pengsida** [comment]
CityscapesVal is evaluated by Cityscapes api.
CityscapesCocoVal is evaluated by coco api.
