### ISSUE TITLE
你好，我对您的注释还是没有完全理解，请问你能再解释一下以下嘛？

### ISSUE THREAD

**Issue by caiyancheng** [zju3dv/snake#156]
![image](https://user-images.githubusercontent.com/70524893/110482361-91823480-8123-11eb-8f16-0c83d23e9cf2.png)
![image](https://user-images.githubusercontent.com/70524893/110482656-dad28400-8123-11eb-89e9-c0555422bdde.png)

**Comment by pengsida** [comment]
act_ind是一张图片的第几个像素，cp_ind是第几个RoI。

**Comment by caiyancheng** [comment]
您好，我想只针对两个类别进行训练，已经改了.yaml文件，但是还是报错（说tensor（8）和（2）不匹配），请问我还需要改哪里呢？
这是我改的：（city_ct_rcnn)
![image](https://user-images.githubusercontent.com/70524893/110636113-dc18b500-81e6-11eb-816e-9fd628130288.png)

**Comment by pengsida** [comment]
你的训练命令是什么。

**Comment by pengsida** [comment]
报错信息也列一下。

**Comment by caiyancheng** [comment]
您好，这是我的训练命令
![image](https://user-images.githubusercontent.com/70524893/110652280-2f92ff00-81f7-11eb-8773-58d6ce4b6ec2.png)
这一步出现了错误：
![image](https://user-images.githubusercontent.com/70524893/110652318-3a4d9400-81f7-11eb-9d85-50b49e41683b.png)
我已经找出来原因：
其中一个是8*8*200*200，一个是8*2*200*200
![image](https://user-images.githubusercontent.com/70524893/110653405-2f473380-81f8-11eb-86cf-d868ba1a4ac7.png)
发现这个是gt(8*8*200*200，就是错的那个)源自于output
所以我目前怀疑是network输出的维度1就是8，所以应该是network的问题

**Comment by caiyancheng** [comment]
不对，我看了一下，最早出现问题应该是在（已经出现了第二个维度是8，所以，或许是dataloader的问题？ )
![image](https://user-images.githubusercontent.com/70524893/110658380-9bc43180-81fc-11eb-83e0-982ca73094a1.png)

**Comment by pengsida** [comment]
是的，我在cityscapes dataloder里把类别数量固定为8：https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/datasets/cityscapes/rcnn_snake.py#L193
你可以改一下。

**Comment by caiyancheng** [comment]
谢谢作者，我还有一个问题：
我将val的数据集改为了CityscapeVal（也就是非COCO格式的标注）
现在他在evaluate的时候这里报了错：
![image](https://user-images.githubusercontent.com/70524893/110746608-01a1cf00-8278-11eb-876a-9fa15cbebd85.png)
他说是output并不存在[py]
请问我可以如何改正呢？

**Comment by caiyancheng** [comment]
![image](https://user-images.githubusercontent.com/70524893/110747816-d8823e00-8279-11eb-80bd-4ee5a1bc55b7.png)

**Comment by pengsida** [comment]
训练rcnn_det训练的是detector，没有预测轮廓，py是轮廓。

**Comment by caiyancheng** [comment]
那在跑这个阶段时是要直接把这一行注释掉吗？
![image](https://user-images.githubusercontent.com/70524893/110751434-d1a9fa00-827e-11eb-8546-34768d543693.png)

**Comment by caiyancheng** [comment]
![image](https://user-images.githubusercontent.com/70524893/110815908-d34ae080-82c5-11eb-8338-11498bb05d35.png)
您好，我想问一下“data","batch"和”max_mem“在这里面的含义

**Comment by pengsida** [comment]
data是加载数据的时间，batch是一个iteration的时间，max_mem占用的显存。
