### ISSUE TITLE
coco_img文件夹的作用

### ISSUE THREAD

**Issue by www195** [zju3dv/snake#159]
作者您好！
我们在运行
        mkdir -p coco_img/train
	cp leftImg8bit/train/*/* coco_img/train
	cp leftImg8bit/val/*/* coco_img/val
	cp leftImg8bit/test/*/* coco_img/test
时产生了疑问。请问coco_img文件夹该放在哪个位置并且有什么作用？

**Comment by pengsida** [comment]
coco_img放在cityscapes目录下。coco api会用到。
