### ISSUE TITLE
关于cityscapes数据集的训练

### ISSUE THREAD

**Issue by Fool-hash** [zju3dv/snake#160]
作者您好！
city_ct_rcnn_.yaml配置文件中的部分代码如下：
    model: 'long_rcnn_det'
    network: 'rcnn_34'
    task: 'ct_rcnn'
在运行以下代码时,
    python train_net.py --cfg_file configs/city_ct_rcnn.yaml model rcnn_det
该代码最后的model rcnn_det与配置文件city_ct_rcnn_.yaml的内容是怎么联系起来的。
类似的，city_rcnn_snake.yaml配置文件中的部分代码如下，
    model: 'long_rcnn'
    network: 'rcnn_34'
    task: 'rcnn_snake'
python train_net.py --cfg_file configs/city_rcnn_snake.yaml model rcnn_snake det_model rcnn_det这句代码最后的
model rcnn_snake det_model rcnn_det与city_rcnn_snake.yaml的内容是怎样联系起来的。

**Comment by pengsida** [comment]
这里处理的 https://github.com/zju3dv/snake/blob/master/lib/config/config.py#L109

**Comment by rainman503** [comment]
您好，请问一下你cityscapes数据集的是怎么摆放的呢
