### ISSUE TITLE
snake and rcnn_snake

### ISSUE THREAD

**Issue by dalanmaobu** [zju3dv/snake#161]
Hello, I'd like to ask what modules are Snake and Deep Snake respectively?

**Comment by dalanmaobu** [comment]
你好，我在配置环境的时候，出现了这个问题：ImportError: ***/snake/snake/lib/csrc/dcn_v2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
我的环境是:CUDA10.0，pytorch 1.1.0，torchvision 0.3

**Comment by pengsida** [comment]
可能是pytorch的cuda版本和系统cuda版本不一样。

**Comment by dalanmaobu** [comment]
我又换了个环境，现在demo可以正常运行，但是运行run.py的时候，出现以下错误：
snake-master/run.py --type evaluate --cfg_file configs/kins_snake.yaml test.dataset KinsVal
load model: data/model/snake/kins/149.pth
loading annotations into memory...
Done (t=1.26s)
creating index...
index created!
loading annotations into memory...
Done (t=1.51s)
creating index...
index created!
  0%|          | 0/7517 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/media/david/fj/wx/snake-master/run.py", line 102, in <module>
    globals()['run_'+args.type]()
  File "/media/david/fj/wx/snake-master/run.py", line 58, in run_evaluate
    for batch in tqdm.tqdm(data_loader):
  File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "lib/datasets/kins/snake.py", line 136, in __getitem__
    height, width = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'



Process finished with exit code 1
我已经检查数据集的位置，没有找到错误

'KinsVal': {
            'id': 'kins',
            'data_root': 'data/kitti/testing/image_2',
            'ann_file': 'data/kitti/testing/instances_val.json',
            'split': 'val'
        },
dataset_catalog.py中数据的位置也没有改动
数据集也是按照格式创建的软连接，请问有什么好的建议吗？

**Comment by pengsida** [comment]
建议打断点debug。

**Comment by singing4you** [comment]
> 我又换了个环境，现在demo可以正常运行，但是运行run.py的时候，出现以下错误：
> snake-master/run.py --type evaluate --cfg_file configs/kins_snake.yaml test.dataset KinsVal
> load model: data/model/snake/kins/149.pth
> loading annotations into memory...
> Done (t=1.26s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=1.51s)
> creating index...
> index created!
> 0%| | 0/7517 [00:00<?, ?it/s]Traceback (most recent call last):
> File "/media/david/fj/wx/snake-master/run.py", line 102, in
> globals()'run_'+args.type
> File "/media/david/fj/wx/snake-master/run.py", line 58, in run_evaluate
> for batch in tqdm.tqdm(data_loader):
> File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/tqdm/_tqdm.py", line 979, in **iter**
> for obj in iterable:
> File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in **next**
> return self._process_data(data)
> File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
> data.reraise()
> File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
> raise self.exc_type(msg)
> AttributeError: Caught AttributeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/david/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "lib/datasets/kins/snake.py", line 136, in **getitem**
> height, width = img.shape[0], img.shape[1]
> AttributeError: 'NoneType' object has no attribute 'shape'
> 
> Process finished with exit code 1
> 我已经检查数据集的位置，没有找到错误
> 
> 'KinsVal': {
> 'id': 'kins',
> 'data_root': 'data/kitti/testing/image_2',
> 'ann_file': 'data/kitti/testing/instances_val.json',
> 'split': 'val'
> },
> dataset_catalog.py中数据的位置也没有改动
> 数据集也是按照格式创建的软连接，请问有什么好的建议吗？

您好，我也遇到了相同的问题，请问您解决了吗？
