### ISSUE TITLE
the results in paper

### ISSUE THREAD

**Issue by feizhaixiaomimei** [zju3dv/snake#166]
作者你好，我最近在看您的论文，运行了您的代码，但是测试之后的结果只显示了平均的AP和AR，我想问一下，怎么得到您论文中关于每个类的AP值，这需要我另做处理吗？

**Comment by pengsida** [comment]
你说的是哪个数据集。

**Comment by feizhaixiaomimei** [comment]
kitti数据集，跑的snake

**Comment by pengsida** [comment]
kitti没有每个类的ap值。
