### ISSUE TITLE
请问其适用于文本数据集码

### ISSUE THREAD

**Issue by 6098669** [zju3dv/snake#167]
文本数据集有孔洞，基于maskrcnn逐像素的不好分割，请问这种基于轮廓的适用于文本数据集吗

**Comment by pengsida** [comment]
我觉得挺适用的。

**Comment by 6098669** [comment]
> 我觉得挺适用的。

但是我看了您在泡泡机器人公开课上说：DeepSnake无法预测有孔的物体，而文本基本上都是带孔的呀

**Comment by pengsida** [comment]
文本检测不用分割文本内部的孔。
