### ISSUE TITLE
作者你好，我是新的学习者，我如何用我做好的coco格式数据集训练这个算法

### ISSUE THREAD

**Issue by lbjy1** [zju3dv/snake#168]
就是我的数据集是一个类，该如何做

**Comment by lbjy1** [comment]
就是我按照#32这个指令python train_net.py --cfg_file snake/sbd_snake.yaml model custom_model train.dataset CocoTrain test.dataset CocoVal
base) lb@lb:~/snake-master$ conda activate snake
(snake) lb@lb:~/snake-master$ python train_net.py --cfg_file snake/sbd_snake.yaml model custom_model train.dataset CocoTrain test.dataset CocoVal
Traceback (most recent call last):
  File "train_net.py", line 1, in <module>
    from lib.config import cfg, args
  File "/home/lb/snake-master/lib/config/__init__.py", line 1, in <module>
    from .config import cfg, args
  File "/home/lb/snake-master/lib/config/config.py", line 109, in <module>
    cfg = make_cfg(args)
  File "/home/lb/snake-master/lib/config/config.py", line 93, in make_cfg
    cfg.merge_from_file(args.cfg_file)
  File "/home/lb/snake-master/lib/config/yacs.py", line 169, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'snake/sbd_snake.yaml'

说文件不存在，sbd snake.yaml不是在configs这个文件里吗

**Comment by lbjy1** [comment]
(snake) lb@lb:~/snake-master$ python train_net.py --cfg_file configs/sbd_snake.yaml model custom_model train.dataset CocoTrain test.dataset CocoVal
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
WARNING: NO MODEL LOADED !!!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 50, in main
    train(cfg, network)
  File "train_net.py", line 25, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/lb/snake-master/lib/train/trainers/trainer.py", line 32, in train
    for iteration, batch in enumerate(data_loader):
  File "/home/lb/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/lb/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "lib/datasets/coco/snake.py", line 139, in __getitem__
    height, width = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by lbjy1** [comment]
作者你好，这个上面是什么问题啦

**Comment by pengsida** [comment]
应该是数据集路径设置有问题。

**Comment by lbjy1** [comment]
class DatasetCatalog(object):
    dataset_attrs = {
        'CocoTrain': {
            'id': 'coco',
            'data_root':'/home/lb/snake-master/data/coco/images/train2017',
            'ann_file':'/home/lb/snake-master/data/coco/annotations/instances_train2017.json',
            'split': 'train'
        },
        'CocoVal': {
            'id': 'coco',
            'data_root':'/home/lb/snake-master/data/coco/images/train2017',
            'ann_file':'/home/lb/snake-master/data/coco/annotations/instances_val2017.json',
            'split': 'test'

我就是按照你这个路径改成自己的路径有问题吗

**Comment by pengsida** [comment]
看起来没问题，我不确定。

**Comment by lbjy1** [comment]
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000


作者你好，
你好我在训练的时候出现这个问题是什么原因啦

**Comment by pengsida** [comment]
可能是训练数据有问题。

**Comment by lbjy1** [comment]
是不是数据集少的缘故额，我26张图片训练，5张验证

**Comment by pengsida** [comment]
也有可能。

**Comment by lbjy1** [comment]
额额，就是我是在做一个裂纹检测能用吗 ，具体是不是用labelme的ploygon来标注吗

**Comment by pengsida** [comment]
应该能用的，可以用labelme标。

**Comment by lbjy1** [comment]
我是不是多用数据能好点，大概200张合适不

**Comment by pengsida** [comment]
你可以试试，训练数据量跟想分割的物体有关系
