### ISSUE TITLE
如何分割我自己的图像数据？

### ISSUE THREAD

**Issue by DeepBrainsMe** [zju3dv/snake#17]
作者你好，请问如何用您的代码和模型，直接分割一张已经得到boundingbox的图片？

**Comment by pengsida** [comment]
开源代码里的snake，用的feature是从detector backbone提取的。
如果是直接输入bounding box + image，需要对image做特征提取，再过snake。
这种setting是和curve gcn一样的: https://arxiv.org/abs/1903.06874

**Comment by LetsGoFir** [comment]
> 开源代码里的snake，用的feature是从detector backbone提取的。
> 如果是直接输入bounding box + image，需要对image做特征提取，再过snake。
> 这种setting是和curve gcn一样的: https://arxiv.org/abs/1903.06874

这个代码比curve gcn快好多，他们train一个epoch要两个小时呢

**Comment by williamwf** [comment]
> > 开源代码里的snake，用的feature是从detector backbone提取的。
> > 如果是直接输入bounding box + image，需要对image做特征提取，再过snake。
> > 这种setting是和curve gcn一样的: https://arxiv.org/abs/1903.06874
> 
> 这个代码比curve gcn快好多，他们train一个epoch要两个小时呢

你好，请问方便分享下curve gcn代码么，申请了一直没回复。谢谢

**Comment by LetsGoFir** [comment]
> > > 开源代码里的snake，用的feature是从detector backbone提取的。
> > > 如果是直接输入bounding box + image，需要对image做特征提取，再过snake。
> > > 这种setting是和curve gcn一样的: https://arxiv.org/abs/1903.06874
> > 
> > 
> > 这个代码比curve gcn快好多，他们train一个epoch要两个小时呢
> 
> 你好，请问方便分享下curve gcn代码么，申请了一直没回复。谢谢

事实上我也没有，只不过他们release了polygon rnn的代码，我认为dataloader是差不多的

**Comment by williamwf** [comment]
> > > > 开源代码里的snake，用的feature是从detector backbone提取的。
> > > > 如果是直接输入bounding box + image，需要对image做特征提取，再过snake。
> > > > 这种setting是和curve gcn一样的: https://arxiv.org/abs/1903.06874
> > > 
> > > 
> > > 这个代码比curve gcn快好多，他们train一个epoch要两个小时呢
> > 
> > 
> > 你好，请问方便分享下curve gcn代码么，申请了一直没回复。谢谢
> 
> 事实上我也没有，只不过他们release了polygon rnn的代码，我认为dataloader是差不多的

还是很感谢！
