### ISSUE TITLE
如何使用cityscapes数据集训练呢？

### ISSUE THREAD

**Issue by rainman503** [zju3dv/snake#174]
作者你好，我把cityscapes的文件夹都放到了指定的位置，但是训练的时候还是报错了。想问一下数据集摆放的结构大概是怎样的呢？然后我看到有一个CityCocoBox里面的数据是把cityscapes的数据转换为coco的格式吗？

**Comment by pengsida** [comment]
1. 数据集的结构：https://github.com/zju3dv/snake/blob/master/INSTALL.md#cityscapes
2. 是的。

**Comment by rainman503** [comment]
好的好的，感谢您的回复，我已经根据文档里的说明运行成功了！
