### ISSUE TITLE
轮廓问题

### ISSUE THREAD

**Issue by lbjy1** [zju3dv/snake#175]
作者你好，这个算法前面多边形轮廓如何可视化。

**Comment by pengsida** [comment]
1. 可视化多边形：https://github.com/zju3dv/snake/blob/master/lib/visualizers/rcnn_snake.py#L62
2. 多边形转为mask：https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/utils/snake/snake_eval_utils.py#L8

**Comment by lbjy1** [comment]
作者你好，那用什么指令可视化啦，我的出错了
