### ISSUE TITLE
关于代码中的一个小错误

### ISSUE THREAD

**Issue by LevinLittleDream** [zju3dv/snake#176]
def draw_umich_gaussian(heatmap, center, radius, k=1):    diameter = 2 * radius + 1    gaussian = gaussian2D((diameter, diameter), sigma=diameter / 6)
    x, y = int(center[0]), int(center[1])

作者您好，这里您的x和y的顺序应该写反了
应该是 y,x = int(center[0]), int(center[1])

**Comment by LevinLittleDream** [comment]
作者您好，我觉得我突然明白了，是因为数据集的标注文件里面的多边形顶点(A,B),其中A对应的是宽度，B对应的是高度，所以其对应的坐标实际上应该是（B，A），是这样的吗

**Comment by pengsida** [comment]
这个由输入决定：https://github.com/zju3dv/snake/blob/master/lib/datasets/cityscapes_coco/snake.py#L84
