### ISSUE TITLE
关于代码中的一个可能的错误

### ISSUE THREAD

**Issue by LevinLittleDream** [zju3dv/snake#177]
if np.random.uniform(0, 1) < 0.5:  
            x_shift = x_min - box[0]
            y_shift = y_min - box[1]
            box = [x_min + x_shift, y_min + y_shift, x_max + x_shift, y_max + y_shift]

作者您好，这里的x_shift应该是box[0] - x_min吧，下面的也一样。
不然的话 按照您此处的代码逻辑 x_min + x_shift = （x_shift + box[0]） + x_shift = box[0] + x_shift

**Comment by LevinLittleDream** [comment]
不好意思，文件的路径是lib/datasets/cityscapes_coco/rcnn_snake.py

**Comment by pengsida** [comment]
这里是在做随机增强。
