### ISSUE TITLE
How to test the performance of the CityScapes Test Set? 

### ISSUE THREAD

**Issue by fh2019ustc** [zju3dv/snake#179]
Hi, thanks for your solid work!

I have a question. That is how to test the performance of the CityScapes Test Set?
I use the command "python run.py --type evaluate --cfg_file configs/city_rcnn_snake.yaml test.dataset CityscapesTest".
And it generate the results in "./data/result/rcnn_snake/long_rcnn/",  as follows,
![image](https://user-images.githubusercontent.com/50725551/119917955-1dc12c80-bf9a-11eb-9376-86b4d1340d60.png)
Are these the files that we should upload to the CityScape Website？

Thank you！

**Comment by pengsida** [comment]
Yes.

**Comment by fh2019ustc** [comment]
Thank you！

**Comment by fh2019ustc** [comment]
Thank you！
