### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by trungpham2606** [zju3dv/snake#18]
@pengsida 
Iam having problem while compiling the library.
Have you met these errors when compiling ?
![image](https://user-images.githubusercontent.com/35657426/75739659-13cd6100-5d38-11ea-8777-e610f2c8e709.png)

**Comment by pengsida** [comment]
I never run the code on Windows, so I do not know which causes this problem.
It looks like that gcc or cuda version is not correct.
