### ISSUE TITLE
训练自己的数据集出现问题

### ISSUE THREAD

**Issue by yyting111** [zju3dv/snake#184]
我用自己的图片按照coco2017的格式制作了数据集，训练报错，请问作者大大要怎么解决呢？

(snake) liuxing@liuxing-ThinkStation-P720:~/snake-master$ sh train.sh
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
WARNING: NO MODEL LOADED !!!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Traceback (most recent call last):
File "train_net.py", line 54, in
main()
File "train_net.py", line 50, in main
train(cfg, network)
File "train_net.py", line 25, in train
trainer.train(epoch, train_loader, optimizer, recorder)
File "/home/liuxing/snake-master/lib/train/trainers/trainer.py", line 32, in train
for iteration, batch in enumerate(data_loader):
File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in next
return self._process_next_batch(batch)
File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in
samples = collate_fn([dataset[i] for i in batch_indices])
File "lib/datasets/coco/snake.py", line 139, in getitem
height, width = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by pengsida** [comment]
看起来是数据集路径没设置正确。

**Comment by yyting111** [comment]
作者大大，我又遇到了新的问题。用自己的图片制作的coco数据集训练好了但是预测的结果和原图一样，可以确认训练好的文件放在了指定的位置，想请问一下是什么情况？

**Comment by pengsida** [comment]
可能是训练数据格式有问题。

**Comment by singing4you** [comment]
> 我用自己的图片按照coco2017的格式制作了数据集，训练报错，请问作者大大要怎么解决呢？
> 
> (snake) liuxing@liuxing-ThinkStation-P720:~/snake-master$ sh train.sh
> loading annotations into memory...
> Done (t=0.02s)
> creating index...
> index created!
> WARNING: NO MODEL LOADED !!!
> loading annotations into memory...
> Done (t=0.01s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=0.01s)
> creating index...
> index created!
> Traceback (most recent call last):
> File "train_net.py", line 54, in
> main()
> File "train_net.py", line 50, in main
> train(cfg, network)
> File "train_net.py", line 25, in train
> trainer.train(epoch, train_loader, optimizer, recorder)
> File "/home/liuxing/snake-master/lib/train/trainers/trainer.py", line 32, in train
> for iteration, batch in enumerate(data_loader):
> File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in next
> return self._process_next_batch(batch)
> File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> AttributeError: Traceback (most recent call last):
> File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "lib/datasets/coco/snake.py", line 139, in getitem
> height, width = img.shape[0], img.shape[1]
> AttributeError: 'NoneType' object has no attribute 'shape'

你好 我训练自己的数据集时也遇到了同样的报错，请问你是怎么解决的呀？

**Comment by singing4you** [comment]
> 我用自己的图片按照coco2017的格式制作了数据集，训练报错，请问作者大大要怎么解决呢？
> 
> (snake) liuxing@liuxing-ThinkStation-P720:~/snake-master$ sh train.sh
> loading annotations into memory...
> Done (t=0.02s)
> creating index...
> index created!
> WARNING: NO MODEL LOADED !!!
> loading annotations into memory...
> Done (t=0.01s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=0.01s)
> creating index...
> index created!
> Traceback (most recent call last):
> File "train_net.py", line 54, in
> main()
> File "train_net.py", line 50, in main
> train(cfg, network)
> File "train_net.py", line 25, in train
> trainer.train(epoch, train_loader, optimizer, recorder)
> File "/home/liuxing/snake-master/lib/train/trainers/trainer.py", line 32, in train
> for iteration, batch in enumerate(data_loader):
> File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in next
> return self._process_next_batch(batch)
> File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> AttributeError: Traceback (most recent call last):
> File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/liuxing/anaconda3/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "lib/datasets/coco/snake.py", line 139, in getitem
> height, width = img.shape[0], img.shape[1]
> AttributeError: 'NoneType' object has no attribute 'shape'

你好，我在训练自己的数据集时也遇到了同样的报错，请问你是怎么解决的呀？
