### ISSUE TITLE
130ms on kitti with GPU

### ISSUE THREAD

**Issue by jinfagang** [zju3dv/snake#19]
I measured forward time around 130 ms on GPU, is this speed normal?

![image](https://user-images.githubusercontent.com/21303438/75745650-f1950c80-5d52-11ea-891a-70afe4c64e98.png)

**Comment by pengsida** [comment]
Yes.
![image](https://user-images.githubusercontent.com/11582122/75749815-afbd9380-5d5d-11ea-871d-fb6ea8c181e5.png)

**Comment by pengsida** [comment]
Measure the speed on Kitti by `python run.py --type network --cfg_file configs/kins_snake.yaml test.dataset KinsVal`

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/75753240-578a8f80-5d65-11ea-8c74-785af7c89055.png)


why using sbd pretrained got no result

**Comment by pengsida** [comment]
Are you sure that you load the pretrained model succussfully?
What result do you get bu running `python run.py --type evaluate --cfg_file configs/sbd_snake.yaml test.dataset SbdVal`.

**Comment by pengsida** [comment]
I found that there was a bug in README.md.
The model need be put at `$ROOT/data/model/snake/sbd/149.pth`, not `$ROOT/data/model/snake/Sbd/149.pth`.
