### ISSUE TITLE
WARNING:NO MODEL LOADED!!!! 段错误（核心已转存）

### ISSUE THREAD

**Issue by ty199931** [zju3dv/snake#194]
I load the .pth and put it in correct position, but when I run the command:python run.py --type evaluate --cfg_file configs/city_rcnn_snake.yaml
it appears, and "段错误（核心已转存）" appears.
Please help me!SOS!!!

**Comment by ty199931** [comment]
I think, maybe the path of somewhere is the problem?  because when i run the demo , the .pth is loaded in “home/ty/bashrc/torch/checkpoints/...pth”，I think it is not normal.

**Comment by ty199931** [comment]
hello? I debug it, and i find it appears error when it run network.cuda，it shows the error :
process finished with exit code139,(interrupted by signal 11:SIGSEGV)

**Comment by pengsida** [comment]
It looks like a problem of pytorch.
Please make sure that the cuda version of pytorch is compatible with that of your system.
