### ISSUE TITLE
作者使用的标注工具是什么呢，json文件内容可以说明一下吗？

### ISSUE THREAD

**Issue by honghande** [zju3dv/snake#20]

**Comment by pengsida** [comment]
这些json文件是coco。
不知道你的数据是怎样的。
我有把SBD数据的图片标注转成coco格式的代码。

**Comment by honghande** [comment]
谢谢作者及时回答，我看了你的cityscapes_anno.tar.gz.这里面的annotations目录中的json文件格式都是coco格式吗？

**Comment by pengsida** [comment]
1. annotations文件夹下的json文件不是coco格式的，coco_ann下的json文件是coco格式的。
2. 我有定义一个dataset，用了coco_ann，因为用coco做evaluation会快一些：https://github.com/zju3dv/snake/blob/master/lib/datasets/dataset_catalog.py#L45
3. SBD没有资源是什么意思。
4. Kitti的json文件是coco格式的，哪些地方奇怪了？

**Comment by honghande** [comment]
谢谢作者及时回复！
1.假设我用labelme标注的json文件，直接转化为coco格式，然后用Kitti方式去训练、测试，评估都可以吗？annotations文件夹下的json文件是用什么标注的呢，主要用来做什么的？因为已经有了coco_ann文件可以作为训练、测试，评估；instance_box_train.json与instance_box_val.json主要是用来做什么的呢？

**Comment by pengsida** [comment]
1. 如果是coco格式，肯定是可以的。可以用Sbd的方式去训练、测试、评估。
2. annotations文件夹下的json文件是每张图片的polygon标注。因为我一开始是照着cityscapes的标注格式做的，后来发现cityscapes official evaluation速度很慢，就换成了coco的格式。
3. instance_box_train.json与instance_box_val.json可以不管。
4. Sbd标注是将官方提供的图片转化成coco格式，我明天把代码传上来。
5. 这文件很大啊，我无法发邮箱。我可以试试传到百度网盘，你能用百度网盘吗？

**Comment by honghande** [comment]
1.我通常会用labelme的标注工具，所以标注格式需要转换为coco格式；

**Comment by honghande** [comment]
1.我通常是用labelme工具去标注的，所以转为coco格式以适配作者模型，
5.我百度网盘是123hjq9，sbd数据我也下载了很卡
作者可以的话加个微信交流一下，再次谢谢你的答复！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pengsida <notifications@github.com&gt;
发送时间: 2020年3月6日 23:33
收件人: zju3dv/snake <snake@noreply.github.com&gt;
抄送: jimi <247607771@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[zju3dv/snake] 作者使用的标注工具是什么呢，json文件内容可以说明一下吗？ (#20)



 
如果是coco格式，肯定是可以的。可以用Sbd的方式去训练、测试、评估。 

annotations文件夹下的json文件是每张图片的polygon标注。因为我一开始是照着cityscapes的标注格式做的，后来发现cityscapes official evaluation速度很慢，就换成了coco的格式。 

instance_box_train.json与instance_box_val.json可以不管。 

Sbd标注是将官方提供的图片转化成coco格式，我明天把代码传上来。 

这文件很大啊，我无法发邮箱。我可以试试传到百度网盘，你能用百度网盘吗？

**Comment by pengsida** [comment]
我把代码上传了
