### ISSUE TITLE
How can I look at the results of each iteration

### ISSUE THREAD

**Issue by dalanmaobu** [zju3dv/snake#200]
Hello, author, I have a question about the code to ask you。How can I look at the results of each iteration in more detail？(作者，您好！害怕英语表述不清晰特用中文进行备注。想问一下每次迭代后的结果，怎么才能看到呢。代码中只能看到最终结果，我想查看每次迭代的结果进行对比。期待您的回答。

**Comment by RicardoCM081924** [comment]
您好，请问您是怎么解决这个问题的？

**Comment by pengsida** [comment]
请阅读代码，然后在每个iteration的输出那里写可视化代码。
