### ISSUE TITLE
关于数据处理中的取点，有一些疑惑

### ISSUE THREAD

**Issue by HsiaX** [zju3dv/snake#206]
作者您好！看到有人用中文提问，为了便于沟通，我也直接用中文提问了，希望您别介意。
看了代码之后，我有以下两个问题：
（1）我注意到在数据处理的时候，对于gt轮廓的采样，是先采样了128*len(poly)，请问后续的操作是分别针对init中采样的128个点，在128*len(poly)中找到与init中每个点距离最近的点，作为最终的迭代回归目标，是这样吗？
（2）第二个问题就是，我在别的提问中有看到说过采样是为了使边缘点采样能够尽量分布均匀，为什么要均匀呢？因为直观来看可能希望比如在边缘比较复杂的地方能够多采样一些点，那么均匀采样是出于好训练的原因吗？

**Comment by pengsida** [comment]
1. gt是这么定义的：
![image](https://user-images.githubusercontent.com/11582122/143184647-6f9c9685-5811-49ad-ad3a-4c750ef0da3e.png)
2. 均匀采样的时候网络更好训练。

**Comment by HsiaX** [comment]
> 1. gt是这么定义的：
>        ![image](https://user-images.githubusercontent.com/11582122/143184647-6f9c9685-5811-49ad-ad3a-4c750ef0da3e.png)
> 
>     2. 均匀采样的时候网络更好训练。

好的，十分感谢！
