### ISSUE TITLE
小目标过滤？

### ISSUE THREAD

**Issue by zhaozhiyi11** [zju3dv/snake#207]
instance_polys = self.transform_original_data(instance_polys, flipped, width, trans_output, inp_out_hw)
instance_polys = self.get_valid_polys(instance_polys, inp_out_hw)
请问这里是进行了过滤的操作吗?具体由哪些操作呢？为什么要做这些操作呢？
谢谢！

**Comment by pengsida** [comment]
1. 这里过滤了太小的物体。
2. 具体操作看代码。
3. 因为有些物体缩放以后小于1个像素。
