### ISSUE TITLE
运行没有反应

### ISSUE THREAD

**Issue by BloodLemonS** [zju3dv/snake#208]
![2021-12-10 09-18-07屏幕截图](https://user-images.githubusercontent.com/56753880/145500933-3de248c4-218f-4fdd-8c98-9246cff232d8.png)
运行的时候没有长时间没有反应是什么原因呢

**Comment by BloodLemonS** [comment]
他的这个运行时间很慢吗？为什么我运行过程中从刚刚那一步到到load model永乐很长时间然后load model也很长时间没有反应

**Comment by BloodLemonS** [comment]
他的这个运行时间很慢吗？为什么我运行过程中从刚刚那一步到到load model用了很长时间然后load model也很长时间没有反应

**Comment by pengsida** [comment]
这个运行不慢。你可以看看代码卡在哪一步了。

**Comment by BloodLemonS** [comment]
![2021-12-11 10-02-46屏幕截图](https://user-images.githubusercontent.com/56753880/145660177-7b26f7ac-a6d3-440e-b2bf-869e072cdb8d.png)
像我这样运行以后长时间没有反应，只有过很长时间以后才会出现下一步，这个问题主要出在那？和配置有关吗？因为我是在anaconda虚拟环境里配置的cuda10.0然后安装的pytorch1.2.0，我的显卡是3060，这个有影响吗
