### ISSUE TITLE
How to turn off data augmentation?

### ISSUE THREAD

**Issue by y2863** [zju3dv/snake#210]
Hi,
I'm having issues with data augmentation generating polygons that crashes the program. This is probably due to different image size, the random scaling and cropping. 

How can I modify the code to turn it off? (https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/datasets/cityscapes_coco/rcnn_snake.py#L191)

Thanks a lot!

**Comment by pengsida** [comment]
Please read the code of function `augment` to see how to revise the code.
