### ISSUE TITLE
snake_config里面的ro的含义？

### ISSUE THREAD

**Issue by KenkunLiu** [zju3dv/snake#216]
![企业微信截图_1643359050860](https://user-images.githubusercontent.com/57042670/151514200-df8cc127-ff04-4029-b03f-b662dea95430.png)

请问evolve.py里面forward函数里面的这几个操作的含义是什么？py_pred为什么要除以snake_config.ro？

**Comment by pengsida** [comment]
ro是ratio的意思，值为4，因为图片经过backbone以后分辨率downsample了4倍。

**Comment by KenkunLiu** [comment]
所以的话，在dataloader里面i_gt_py已经被缩小了4倍，然后这里的话 'i_gt_py': output['i_gt_py'] * snake_config.ro 是使得contour在原分辨率上进行supervision的，所以py_pred才需要除以4，我的理解对吗？

**Comment by pengsida** [comment]
对的。
