### ISSUE TITLE
数据部分疑问

### ISSUE THREAD

**Issue by linuxd234** [zju3dv/snake#219]
作者您好，请问大佬在lib/datasets/coco/snake.py中的：

 orig_img, inp, trans_input, trans_output, flipped, center, scale, inp_out_hw = \
            snake_coco_utils.augment(
                img, self.split,
                snake_config.data_rng, snake_config.eig_val, snake_config.eig_vec,
                snake_config.mean, snake_config.std, instance_polys
            )

部分
snake_config.data_rng, snake_config.eig_val, snake_config.eig_vec 这几个参数是控制什么的呢？

**Comment by pengsida** [comment]
这几个参数用来做data augmentation的：https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/utils/data_utils.py#L176

**Comment by linuxd234** [comment]
谢谢大佬！

**Comment by linuxd234** [comment]
> 这几个参数用来做data augmentation的：
> 
> https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/utils/data_utils.py#L176

谢谢大佬！
