### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Network

### ISSUE THREAD

**Issue by BloodLemonS** [zju3dv/snake#220]
您好，在运行demo的时候遇见size mismatch的问题是什么原因呢？
![image](https://user-images.githubusercontent.com/56753880/153986119-d1168d4d-76bd-43df-aed4-a98cd09e26c9.png)

**Comment by pengsida** [comment]
你pre-trained model下载错了。demo要求sbd数据集的pre-trained model。
