### ISSUE TITLE
关于测试部分的问题

### ISSUE THREAD

**Issue by TzzLongwind** [zju3dv/snake#222]
最近我想上传到cityscape官网上,对测试集进行测评,我对验证代码进行了修改用于测试,但是在第204张图片时,会出现RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM的错误.请问作者对此有什么解决方案吗?或者有用于对测试集的预测与格式转换代码吗?十分感谢!

**Comment by pengsida** [comment]
可能是网络的输出为空导致的。你可以看看是哪里的代码报错的。
