### ISSUE TITLE
Direction of Octagon Initalization

### ISSUE THREAD

**Issue by EthanHNguyen** [zju3dv/snake#224]
Thanks for your great work on DeepSnake. I am experimenting with alternative contour proposal methods. 

When loading the contours for training, the clockwise polygons are obtained [Source](https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/datasets/cityscapes/snake.py#L48). 

However, when preparing the octagon, the points are initialized counter-clockwise [Source](https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/datasets/cityscapes/snake.py#L102).  

**Does the direction of the contour proposal (Clockwise versus Counter-Clockwise) matter?**

**Comment by EthanHNguyen** [comment]
**Example:**
Octagon Initialization
<img width="485" alt="Screen Shot 2022-02-23 at 7 39 18 PM" src="https://user-images.githubusercontent.com/23198915/155385985-5cbe70ce-5e94-4126-89f9-98c68233a0f9.png">

Ground Truth
<img width="484" alt="image" src="https://user-images.githubusercontent.com/23198915/155386000-0fb90f02-0338-4936-a945-b960f7039fb3.png">

The contours follow different directions.

**Comment by pengsida** [comment]
The direction of the contour proposal (Clockwise versus Counter-Clockwise) matters.

**Comment by EthanHNguyen** [comment]
Thanks! Which direction is the right direction? 

If I understand correctly, your code seems to propose in opposing directions.

**Comment by pengsida** [comment]
The directions of two polygons are the same.
I checked it previously.
This code gets clockwise polygons: https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/datasets/cityscapes/snake.py#L48

**Comment by pengsida** [comment]
You could use this code to check the direction of a polygon: https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/utils/snake/snake_cityscapes_utils.py#L293
