### ISSUE TITLE
训练的时候初始化报错

### ISSUE THREAD

**Issue by ImmortalCi** [zju3dv/snake#226]
我已经在环境里安装好pillow库了，但是在运行训练代码：python train_net.py --cfg_file configs/sbd_snake.yaml model sbd_snake
的时候，还会报错，要求我安装pillow库，是什么原因呢？
<img width="852" alt="image" src="https://user-images.githubusercontent.com/74886609/156384266-c4ec5c8c-20f8-4e12-8763-285c62f9c5c7.png">
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/74886609/156384349-f88017c7-94a3-4965-9e5c-91f5a189cc82.png">

**Comment by pengsida** [comment]
请谷歌搜索安装pillow的问题。

**Comment by bamboopu** [comment]
> 请谷歌搜索安装pillow的问题。

前辈回答好贴心！！！200多个issue逐一过，太强了！

**Comment by Gorgerbin** [comment]
你好，我也遇到了这个问题，请问你解决了吗？

**Comment by zhangyicodes** [comment]
我也遇到了这个问题，但是环境中确实已经安装pillow了

**Comment by zhangyicodes** [comment]
> 我也遇到了这个问题，但是环境中确实已经安装pillow了

降低pillow版本为6.2.1可以解决问题
