### ISSUE TITLE
the problem of the extreme_utils 

### ISSUE THREAD

**Issue by PanXiongAdam** [zju3dv/snake#229]
Hello, i have a issue about the extreme_utils. I follow the steps of the install, but it can't  
![image](https://user-images.githubusercontent.com/32896464/173191921-93386265-e82f-4441-8e3e-450af50117ca.png)
I test it in difference  environment. I run it: cd ./layers/extreme_utils && export CUDA_HOME="/usr/local/cuda-10.1" && python setup.py build_ext --inplace
![image](https://user-images.githubusercontent.com/32896464/173192004-d22a029d-8536-4588-84eb-c5ea2e87dc1d.png)

**Comment by pengsida** [comment]
It seems that you succeeded to compile the code.
Maybe it is caused by the incorrect usge of python environment.
