### ISSUE TITLE
How to Test on a single image?

### ISSUE THREAD

**Issue by ForestWang** [zju3dv/snake#23]
RT, thanks very much.

**Comment by pengsida** [comment]
Do you mean to test on your own image?

**Comment by ForestWang** [comment]
yes. means inputing an image and do inference. not evaluate on benchmarks.

**Comment by pengsida** [comment]
I will add this function tonight.

**Comment by pengsida** [comment]
I have updated the code https://github.com/zju3dv/snake#demo

**Comment by ForestWang** [comment]
copy that, thanks very much!
