### ISSUE TITLE
change backbone to dla102

### ISSUE THREAD

**Issue by xinzaishi** [zju3dv/snake#231]
Hi, [pengsida]
I want to change the backbone from dla34 to dla102. I meet the weights and input shape mismatch. To solve this, I add a conv kernel just like you define self.envolve_fuse = nn.Conv1d(128, 64, 1). And pust in the evolve_poly func. the training process seems like ok. Yet I am not sure is it ok?
![evolve](https://user-images.githubusercontent.com/22416369/176661889-3e09f3ff-5f08-45fc-8300-e3b1c0799954.png)

**Comment by pengsida** [comment]
It is ok.

**Comment by xiannsa** [comment]
@xinzaishi   Hello! I encountered the issue you described when I was trying to change "dla-34" to "dla60". Do you know how to resolve this error?
![XG{6_HD)~4S8VL6WTE0VL9C](https://github.com/zju3dv/snake/assets/108583027/39dc1981-c75b-4da8-84ca-159f4d9c8015)
