### ISSUE TITLE
get_affine_transform() is buggy

### ISSUE THREAD

**Issue by nnop** [zju3dv/snake#234]
The `get_affine_transform()` function seems buggy and appear in many github repos.

https://github.com/zju3dv/snake/blob/2c9b0a6788a9fd38e95a22e2ac7aabbb1a9303c5/lib/utils/data_utils.py#L138-L139

It should be `src_h` and `dst_h` for the y coordinate.

https://github.com/Jeff-sjtu/HybrIK/issues/118

**Comment by pengsida** [comment]
Using this function should be careful about the input.
