### ISSUE TITLE
I can not find those files, can you help me ?

### ISSUE THREAD

**Issue by H-0813** [zju3dv/snake#235]
Thanks for your great work, but when I run this code "python train_net.py --cfg_file configs/city_ct_rcnn.yaml model rcnn_det".
I can not find "make_trainer, make_optimizer, make_lr_scheduler, make_recorder, set_lr_scheduler" from lib.train
Can you help me ?  
Tranks for your reply.

**Comment by pengsida** [comment]
Maybe the python version is incorrect.
