### ISSUE TITLE
Mask map

### ISSUE THREAD

**Issue by lks0825** [zju3dv/snake#238]
Dear author, what files should I modify to generate the segmentation mask?

**Comment by pengsida** [comment]
Your question is unclear. Please describe it in more details, such as what data, the predicted segmentation mask or the ground-truth segmentation mask.

**Comment by lks0825** [comment]
When using the SBD dataset, I then want to output the predicted segmentation mask map

**Comment by pengsida** [comment]
Please read the visualization code.
