### ISSUE TITLE
更换backbone

### ISSUE THREAD

**Issue by xiannsa** [zju3dv/snake#239]
大佬你好，请问如果我想要更换centernet 的 dla34 backbone 需要修改那个位置，还有你有推荐的可以替换的网络吗？

**Comment by pengsida** [comment]
你好，修改这个位置：https://github.com/zju3dv/snake/blob/master/lib/networks/ct_rcnn/ct_rcnn.py#L14

**Comment by pengsida** [comment]
我不太了解现在最好的backbone网络。

**Comment by xiannsa** [comment]
感谢解答，我还想知道network目录下面的ct_rcnn、rcnn_snake和snake都是做什么作用的呢
![image](https://github.com/zju3dv/snake/assets/108583027/a3b9d881-f2d7-4a14-b74e-7a2ae7f44f3d)

**Comment by xiannsa** [comment]
感谢解答，我还想知道network目录下面的ct_rcnn、rcnn_snake和snake都是做什么作用的呢，有什么不一样
![9O(3OE)$6QLG_90Q1WV`A70](https://github.com/zju3dv/snake/assets/108583027/8f908aaf-d1bc-4b31-88c5-cbe72e48b9c0)

**Comment by pengsida** [comment]
是不同的配置文件选择的不同的网络文件。具体请看README中列出来的命令。
