### ISSUE TITLE
why didn't you choose to use FPN as your backbone?

### ISSUE THREAD

**Issue by TengFeiHan0** [zju3dv/snake#24]
At first glance, you have chosen a traditional strategy known as  "detect and segment" widely used in previous methods. I was wondering why didn't you choose FPN to acquire multiple-level information or follow the style of FCOS?

**Comment by pengsida** [comment]
We use CenterNet as our detector, which does not adopt FPN as the backbone.
I did not consider much about the network architecture.

**Comment by huaze555** [comment]
@pengsida the CenterNet you means is "CenterNet: Object Detection with Keypoint Triplets." or  "Objects as Points."?

**Comment by pengsida** [comment]
Objects as Points
