### ISSUE TITLE
修改loss函数

### ISSUE THREAD

**Issue by xiannsa** [zju3dv/snake#240]
大佬你好，请问要想修改loss函数，应该在哪个文件修改？ 我想使用Siou，这个可以用在snake上面吗？

**Comment by pengsida** [comment]
需要看你使用的config文件调用了哪个trainer file，一般是下面两个中的一个：
1. https://github.com/zju3dv/snake/blob/master/lib/train/trainers/snake.py
2. https://github.com/zju3dv/snake/blob/master/lib/train/trainers/rcnn_snake.py
