### ISSUE TITLE
对比实验评估问题

### ISSUE THREAD

**Issue by xiannsa** [zju3dv/snake#241]
大佬你好，我在使用deepsnake做对比实验的时候遇到别的算法包含AR-50(平均召回率)但没有AR-50:95，而snake只有AR-50:95，请问有方法可以解决吗，可以的话要修改哪个地方呢？  麻烦大佬解答

**Comment by pengsida** [comment]
改COCOeval里的代码吧：https://github.com/zju3dv/snake/blob/master/lib/evaluators/coco/snake.py#L9
