### ISSUE TITLE
 “THC/THC.h”: No such file or directory

### ISSUE THREAD

**Issue by LiuReboot** [zju3dv/snake#244]
在编译extreme_utils出现的这个问题，我知道这个问题可能是由于pytorch版本太高产生的。但是在3090平台上pytorch和cuda版本必须使用高版本，我请问作者大大有什么方法可以使代码在3090这样的平台编译成功呢？
C:/Users/cwnu/anaconda3/envs/py37/lib/site-packages/torch/include\c10/macros/Macros.h(142): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
D:\PythonProject\snake-master\lib\csrc\extreme_utils\src\nms.cu(5): fatal error C1083: 无法打开包括文件: “THC/THC.h”: No such file or directory
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\bin\\nvcc.exe' failed with exit status 2

**Comment by ZitengXue** [comment]
请问老哥解决了吗？我也是在3090上由于pytorch版本太高编译不通过

**Comment by LiuReboot** [comment]
> 请问老哥解决了吗？我也是在3090上由于pytorch版本太高编译不通过

可以使用高版本的DCNv2，在DCNv2的GitHub上能找到。

**Comment by ZitengXue** [comment]
谢谢老哥！ 还想问一下您编译apex也是用的最新的吗还是作者给的那个git checkout 39e153a3159724432257a8fc118807b359f4d1c8版本

**Comment by ZitengXue** [comment]
> > 请问老哥解决了吗？我也是在3090上由于pytorch版本太高编译不通过
> 
> 可以使用高版本的DCNv2，在DCNv2的GitHub上能找到。

谢谢老哥！ 还想问一下您编译apex也是用的最新的吗还是作者给的那个git checkout 39e153a3159724432257a8fc118807b359f4d1c8版本

**Comment by LiuReboot** [comment]
> > > 请问老哥解决了吗？我也是在3090上由于pytorch版本太高编译不通过
> > 
> > 
> > 可以使用高版本的DCNv2，在DCNv2的GitHub上能找到。
> 
> 谢谢老哥！ 还想问一下您编译apex也是用的最新的吗还是作者给的那个git checkout 39e153a3159724432257a8fc118807b359f4d1c8版本

这个是用Ubuntu系统才用这个命令，如果你是Windows的话不用这个命令，在csdn上有这个Deep Snake详细的配置环境的教程。

**Comment by ZitengXue** [comment]
> > > > 请问老哥解决了吗？我也是在3090上由于pytorch版本太高编译不通过
> > > 
> > > 
> > > 可以使用高版本的DCNv2，在DCNv2的GitHub上能找到。
> > 
> > 
> > 谢谢老哥！ 还想问一下您编译apex也是用的最新的吗还是作者给的那个git checkout 39e153a3159724432257a8fc118807b359f4d1c8版本
> 
> 这个是用Ubuntu系统才用这个命令，如果你是Windows的话不用这个命令，在csdn上有这个Deep Snake详细的配置环境的教程。

好嘞谢谢老哥！
