### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by XiaoWen-AI** [zju3dv/snake#25]
It's a nice idea, but I can't install this project in Windows10, and every "requirement" are satisfied. Follow the INSTALL.md， “install apex" ” have error " C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include\crt/host_config.h(133): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! **Only the versions 2012, 2013, 2015 and 2017 are supported!**
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin\\nvcc.exe' failed with exit status 2". I have installed VS2017 and VS2019. Do you know what's the problem? Or how to change to VS2017

**Comment by XiaoWen-AI** [comment]
After uninstall VS2019, have the same error
Supplementary error information:
"
...
running build_ext
C:\ProgramData\Anaconda3\envs\snake\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'amp_C' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe ..."

**Comment by pengsida** [comment]
Use Ubuntu 16.04.
I do not know how to install the code on Windows.
