### ISSUE TITLE
如何能够在目标检测的框上面显示类别

### ISSUE THREAD

**Issue by xiannsa** [zju3dv/snake#250]
请问，修改什么地方的代码可以实现轮廓分割和目标检测并显示类别名呢？

**Comment by xiannsa** [comment]
我看到cityspaces上面有分类，coco好像没有

**Comment by pengsida** [comment]
在这里添加增加文字的代码: https://github.com/zju3dv/snake/blob/master/lib/visualizers/snake.py#L81
如何画文字：https://stackoverflow.com/questions/8482588/putting-text-in-top-left-corner-of-matplotlib-plot
