### ISSUE TITLE
dance这篇论文在snake的基础上改进，修改了损失函数

### ISSUE THREAD

**Issue by xiannsa** [zju3dv/snake#251]
大佬你好，dance的作者在snake的轮廓变形基础上加入了标准化，然后他的损失函数在原本的基础上做了一点修改，我想知道是修改哪个地方的代码呢？
![image](https://github.com/zju3dv/snake/assets/108583027/a5d44516-3dc3-47d8-9a62-c9f7be04d4f6)

**Comment by pengsida** [comment]
你好，请在dance的repo里提问。
