### ISSUE TITLE
请问作者每一次迭代的效果图在代码中是怎么实现的

### ISSUE THREAD

**Issue by LiuReboot** [zju3dv/snake#253]
请问作者每一次迭代的效果图在代码中是怎么实现的。从初始轮廓的生成到第三次迭代生成的最终效果图，在代码中是怎么实现的。
![屏幕截图 2023-12-04 111639](https://github.com/zju3dv/snake/assets/66234181/55f360b8-b3a4-4f0b-bdb0-308543df30b4)

**Comment by pengsida** [comment]
获得每次iteration输出的polygon，然后可视化相应的polygon就行。
