### ISSUE TITLE
Error when testing 

### ISSUE THREAD

**Issue by tunghustvn** [zju3dv/snake#26]
Hi. Thank you very much for your contribution.
I have a problem while running the testing code below:
`python run.py --type evaluate --cfg_file configs/city_rcnn_snake.yaml`
Below is the error prompted:
**ImportError: /home/tunghandsome/Tung/snake/snake/lib/csrc/dcn_v2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E**
Does anyone know how to fix this error?
```
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 51, in run_evaluate
    network = make_network(cfg).cuda()
  File "/home/tunghandsome/Tung/snake/snake/lib/networks/make_network.py", line 23, in make_network
    return imp.load_source(module, path).get_network(cfg)
  File "/home/tunghandsome/snake/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "lib/networks/rcnn_snake/__init__.py", line 1, in <module>
    from .ct_rcnn_snake import get_network as get_rcnn
  File "lib/networks/rcnn_snake/ct_rcnn_snake.py", line 2, in <module>
    from .dla import DLASeg
  File "lib/networks/rcnn_snake/dla.py", line 16, in <module>
    from lib.networks.dcn_v2 import DCN
  File "/home/tunghandsome/Tung/snake/snake/lib/networks/dcn_v2.py", line 13, in <module>
    from lib.csrc.dcn_v2 import _ext as _backend
ImportError: /home/tunghandsome/Tung/snake/snake/lib/csrc/dcn_v2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
```

**Comment by pengsida** [comment]
What are the versions of your system cuda and pytorch cuda?

**Comment by tunghustvn** [comment]
The version of my system cuda is 10.2; my pytorch cuda is 10.1.

**Comment by pengsida** [comment]
Make sure two points:
1. pytorch version that you used to compile the code should be the same as the one you use to run the code.
2. The version of pytorch cuda should be the same as that of the system cuda.

**Comment by tunghustvn** [comment]
But I'm running your project on a server GPU which installed CUDA 10.2 already while the [Pytorch official website](https://pytorch.org/) only provide the introduction for installing CUDA upto 10.1.
Does anyone know how to install Pytorch with CUDA 10.2 from source? Thanks.

**Comment by pengsida** [comment]
Are you sure that the pytorch version that you used to compile the code is the same as the one you use to run the code?

**Comment by tunghustvn** [comment]
@pengsida how can I check these versions? Sorry, I'm just a newbie.
Maybe the pytorch version which I used to compile the code is 1.4.0 and cuda 10.1
When I run **setup.py** in apex, the terminal display this:
`torch.__version__  =  1.4.0
setup.py:46: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
  warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
from /usr/local/cuda/bin`

**Comment by pengsida** [comment]
`python -c "import torch; print(torch.version.cuda)"`
`nvcc --version`

**Comment by tunghustvn** [comment]
> `python -c "import torch; print(torch.version.cuda)"`
> `nvcc --version`

I ran these two command and recieved 2 responses, respectively:
`10.1`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
But when I ran the testing command, the error still happened. Any idea?

**Comment by pengsida** [comment]
How about re-compling this module: `python setup.py build_ext --inplace`.

**Comment by tunghustvn** [comment]
> How about re-compling this module: `python setup.py build_ext --inplace`.

I re-compiled dcn_v2, extreme_utils, roi_align_layer followed the INSTALL.md but the error still appeared.

**Comment by pengsida** [comment]
Did you set `export CUDA_HOME="/usr/local/cuda-9.0`?
If your cuda is 10.0, it might cause errors.

**Comment by tunghustvn** [comment]
No. Depend on my GPU, I set CUDA_HOME="/usr/local/cuda"

**Comment by pengsida** [comment]
You could test pytorch 1.1 and cuda 9.0, as described in INSTALL.md, to see if this problem is caused by the pytorch version and cuda version.

**Comment by tunghustvn** [comment]
I deleted and reinstalled the entire project and finally it worked. Maybe I got problem when building.
I confirm that snake can be run on CUDA 0.1 + Pytorch 1.4.
Thanks for your support.

**Comment by Pursuer1030** [comment]
Hello，I  installed the project on CUDA10.1 + Pytorch 1.4. But it still report this mistake in training. Can you provide your installation details? I don't know which step is wrong

**Comment by Pursuer1030** [comment]
I installed this project on CUDA10.1 and Pytorch1.4. But it still reports this mistake in training. Can you provide the installation details? I don't know which step is wrong.

**Comment by pengsida** [comment]
What is the mistake in training?
