### ISSUE TITLE
I have trouble when I'm installing

### ISSUE THREAD

**Issue by evan0621** [zju3dv/snake#28]
Windows10
Python3.7

> cd dcn_v2
python setup.py build_ext --inplace
cd ../extreme_utils
python setup.py build_ext --inplace

when I enter 
`python setup.py build_ext --inplace`
I got diffirent error from each of them

cd dcn_v2:
> dcn_v2_cuda.obj : error LNK2001: 無法解析的外部符號 "struct THCState * state" (?state@@3PEAUTHCState@@EA)
build\lib.win-amd64-3.7\_ext.cp37-win_amd64.pyd : fatal error LNK1120: 1 個無法解析的外部符號
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

cd extreme_utils:
> 6 errors detected in the compilation of "C:/Users/evans/AppData/Local/Temp/tmpxft_000000e8_00000000-8_utils.cpp4.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2

**Comment by pengsida** [comment]
Use Ubuntu 16.04.
I do not know how to install the code on Windows.

**Comment by evan0621** [comment]
OK I'll try. Thanks!
