### ISSUE TITLE
Request for tutorial or instructions for train this algorithm on other format of dataset

### ISSUE THREAD

**Issue by RonDen** [zju3dv/snake#29]
Excellent and inspiring work it is! 
But I wander how to train and apply the algorithm on 
my own instance segmentation dataset ?

I want to use this algorithm for cells and nucleus instance segmentation. The instance is annotated
with `.png` format or the widely used `.json`.

I have download and carefully reviewed your code and project structure but it is too complicated and there is little comment about how the code works or the return result of the function.

Can you give some instructions or tutorials like the popular used repo: https://github.com/matterport/Mask_RCNN 

I think it will be a nice work and inspre more wonderful ideas. Thank for your contribution to the community again.

**Comment by pengsida** [comment]
Could share a subset of your data (images and json files)?
I will write some instructions on how to train the network on the custom dataset.

**Comment by RonDen** [comment]
Thank you for your respones!

The dataset I use have been converted into the popular used coco `json` format.
I wander is coco format supported? I haven't seen evaluation and comparision on coco dataset like the most instance segmentation papers.

Is that supported now?

**Comment by RonDen** [comment]
![image](https://user-images.githubusercontent.com/29707503/79857620-a4532400-8400-11ea-8fee-f871dd01242f.png)

The dataset I use is like this. Very simple, only two classes in there.

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/issues/32
