### ISSUE TITLE
Testing on Kitti dataset failing 

### ISSUE THREAD

**Issue by DesperateMaker** [zju3dv/snake#37]
I`m interested in this project. And tried to deploy it, but visualisation failing every time in the same point. 
![image](https://user-images.githubusercontent.com/37222767/80012583-31b47800-84d6-11ea-9af0-725e963f505c.png)
This error could be healed by downgrading tqdm to 4.19 instead ~4.25 or upgrading to 4.40+. But there are strange another error in same place 
![image](https://user-images.githubusercontent.com/37222767/80012805-8b1ca700-84d6-11ea-883b-879f39baf43e.png)
Do you know anything about this? 

I use nvidia tesla, cuda-10, i`ve compiled apex and _ext from install.md instruction. 
And pytorch is convinient to cuda version: https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.whl

**Comment by pengsida** [comment]
Do you use `plt.save()` without `plt.close()`?

**Comment by DesperateMaker** [comment]
I didn't touch code yet, just intalled according instructions

**Comment by pengsida** [comment]
What is your command?

**Comment by DesperateMaker** [comment]
Visualize(on kitti dataset):

python run.py --type visualize --cfg_file configs/kins_snake.yaml test.dataset KinsVal ct_score 0.3

**Comment by pengsida** [comment]
Did it show images?

**Comment by DesperateMaker** [comment]
no, I ran it on remote server via cli. am I a bit stupid?)

**Comment by pengsida** [comment]
You could try the evaluation.
