### ISSUE TITLE
The values of kinds of APs during training are 0?

### ISSUE THREAD

**Issue by bubuBlack** [zju3dv/snake#38]
Hello, I have converted my own data set to the coco data set format and modified the data path, but during the training process, the loss is changing, but all ap, ar values are almost 0 ,the result of visualization is equivalent to the original image, without any detection frame and segmentation effect. I think the data set is not really trained, have I missed any parameter adjustment?

**Comment by pengsida** [comment]
Use `tensorboard --logdir data/record/snake` to see the training status.
