### ISSUE TITLE
boxes + image 作为 Input 如何实现

### ISSUE THREAD

**Issue by aisegmentcn** [zju3dv/snake#39]
感谢作者优秀的工作！
请问，能否写个输入是boxes 和 image时的demo？

是否仅需要修改ct_snake.py的forward函数的
ct, detection = self.decode_detection(output, cnn_feature.size(2), cnn_feature.size(3))
这条语句，由外部输入的boxes来生成ct。
谢谢！

**Comment by pengsida** [comment]
嗯嗯，由外部输入的boxes来生成detection。
我这几天有空写一下，你也可以先自己试着实现下。
如果是自动化标注的工作，可能像Curve GCN一样把图片crop and resize的效果可能更好。

**Comment by aisegmentcn** [comment]
我们自己尝试了一下，还没调通（捂脸），坐等大神。
另外，我们的boxes有时不会完全包围待分割物体，只包围大部分，所以直接crop and resize可能不行。

**Comment by pengsida** [comment]
哦哦，那可以针对你们数据的情况做些data  augmentation和相应的训练，这样效果可能更好。
我这几天写一下输入是boxes 和 image时的demo。

**Comment by aisegmentcn** [comment]
非常感谢！！！

**Comment by pengsida** [comment]
抱歉，我忘了这件事。我这周末会写好。

**Comment by aisegmentcn** [comment]
感谢！非常感谢！

**Comment by pengsida** [comment]
我加了这个功能。
`python run.py --type visualize --cfg_file configs/sbd_snake.yaml test.dataset SbdVal ct_score 0.3 use_gt_det False`.
代码在 https://github.com/zju3dv/snake/blob/master/lib/networks/snake/ct_snake.py#L30

**Comment by aisegmentcn** [comment]
OK，多谢
