### ISSUE TITLE
why not test on coco?

### ISSUE THREAD

**Issue by txytju** [zju3dv/snake#4]
Why don't you show results on coco dataset?

**Comment by pengsida** [comment]
Recently I have been perform experiments on coco.
I found that centernet did not achieve a satisfactory performance on coco.
I have been trying to add snake on other detectors.

**Comment by MachineSzy** [comment]
作者您好，请问您已经实现其他detector的snake了吗？想学习一下

**Comment by pengsida** [comment]
我实现了，但没整理代码。
