### ISSUE TITLE
few confusions on paper

### ISSUE THREAD

**Issue by Zhang-O** [zju3dv/snake#41]
vignette:  “Figure 7 shows some qualitative results on Kins. ” in page 7 should be
“Figure 6 (row 3) shows some qualitative results on Kins. ”

I am confused 
how to understand amodal and  inmodal or modal in accurate chinese?

**Comment by pengsida** [comment]
1. I have corrected the typo in the latest version of the paper.
2. inmodal: 正常的instance segmentation。amodal: 不考虑遮挡的instance segementation，需要恢复出被遮挡的部分。

**Comment by Zhang-O** [comment]
> 1. I have corrected the typo in the latest version of the paper.
> 2. inmodal: 正常的instance segmentation。amodal: 不考虑遮挡的instance segementation，需要恢复出被遮挡的部分。

3q!  where can I find the explanations of  professional words like these? I have searched these words using several softwares such as biying dict, youdao dict, google translate, but go no satisfied result.

**Comment by pengsida** [comment]
https://arxiv.org/pdf/1604.08202.pdf
