### ISSUE TITLE
Validation data load error. Should num_worker be 0?

### ISSUE THREAD

**Issue by RonDen** [zju3dv/snake#45]
I constantly get this error in almost every 4-5 epoch training.
```bash
Traceback (most recent call last):
  File "train_net.py", line 57, in <module>
    main()
  File "train_net.py", line 53, in main
    train(cfg, network)
  File "train_net.py", line 35, in train
    trainer.val(epoch, val_loader, evaluator, recorder)
  File "/ldap_shared/home/s_zyt/inseg/code/snake/lib/train/trainers/trainer.py", line 76, in val
    for batch in tqdm.tqdm(data_loader):
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/ldap_shared/home/s_zyt/inseg/code/snake/lib/datasets/collate_batch.py", line 7, in snake_collator
    ret = {'inp': default_collate([b['inp'] for b in batch])}
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 65, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/ldap_shared/home/s_zyt/.pyenv/versions/anaconda3-2019.07/envs/snake/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 544 and 480 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:689
```

Should the  validation dataloader worker number be set as 0?
Previously, I got this error in train dataloader, so I set the num_worker=0, it works.

Configuration as follow:
```yaml
train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120, 150, 170)
    gamma: 0.5
    batch_size: 16
    dataset: 'CocoTrain'
    num_workers: 0
    epoch: 150
test:
    # dataset: 'SbdMini'
    dataset: 'CocoVal'
    batch_size: 16
    num_workers: 0
```

My operating system is Ubuntu16.04.
Thank you!

**Comment by pengsida** [comment]
No, it looks like not a problem of dataloader worker.
Maybe there is some problem in your evaluation data.
Use `python run.py --type evaluate --config_file your_config_file_path` to reproduce this bug.
It occurs at `File "/ldap_shared/home/s_zyt/inseg/code/snake/lib/datasets/collate_batch.py", line 7`

**Comment by RonDen** [comment]
Yes, actually I use the code reproduced this bug.
```bash
python run.py --type evaluate --cfg_file configs/sbd_snake.yaml model custom_model train.dataset CocoTrain test.dataset CocoVal
```

But I have no idea why would this happend, the dataset I use can be trained on other model like the mmdet version mask rcnn.

**Comment by RonDen** [comment]
I think maybe the image passed into function `default_collate` must have the same shape.
My problem is their shapes are not the same.
```
>>> [b['inp'].shape for b in batch]
[(3, 544, 800), (3, 480, 608), (3, 544, 800), (3, 544, 800), (3, 544, 800), (3, 544, 800), (3, 544, 800), (3, 448, 608), (3, 544, 800), (3, 544, 800), (3, 544, 800), (3, 544, 800), (3, 544, 800), (3, 448, 608), ...]
>>> default_collate(a)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 544 and 480 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:689
```

**Comment by pengsida** [comment]
Set `batch_size = 1` in `test`.
Our code does not support batch evaluation.

**Comment by RonDen** [comment]
I fixed this problem and the network training is on going.

But I think the training process is very slow and the GPU utilization rate is very low. I have two 2080ti GPU card, but the `GPU-Util` is 0% in most of the time.
![image](https://user-images.githubusercontent.com/29707503/82972131-e9253880-a006-11ea-8f72-64609d3efd9a.png)

Is that because of the `CirConv` not being fully optimized by the modern dl framework pytorch?
Or other problem.

I wander how long it will take for your training on `coco` or `sbd` dataset?
My dataset is far smaller than them but it also take almost two days. 
training `batchsize=16`.

**Comment by pengsida** [comment]
Set a bigger num_workers.
The data loading of your training is very slow.
![image](https://user-images.githubusercontent.com/11582122/82974013-78cce600-a00b-11ea-89cf-4624553fce8c.png)

**Comment by pengsida** [comment]
The training on sbd takes about 8 hours.
