### ISSUE TITLE
Pre-trained model in long_rcnn_det folder for CityScapes 

### ISSUE THREAD

**Issue by xiamingfu** [zju3dv/snake#46]
It seems the pre-trained detection model  for CityScapes  is not provided?
Sincerely thank you!

**Comment by pengsida** [comment]
Yes, the detection model is included in the final model.
Did you encounter any problem?

**Comment by xiamingfu** [comment]
Yes,there was  a problem when the 'demo' code was run  with provided CityScapes pre-trained model.
It seems that the folder named 'long_rcnn_det' should include a detection model just as provided 197.pth under 'long_rcnn' folder. However, there is a mere model provided in CityScapes part.Did I misunderstand it?
Sincerely thanks!

**Comment by xiamingfu** [comment]
> Yes, the detection model is included in the final model.
> Did you encounter any problem?

Yes,there was a problem when the 'demo' code was run with provided CityScapes pre-trained model.
It seems that the folder named 'long_rcnn_det' should include a detection model just as provided 197.pth under 'long_rcnn' folder. However, there is a mere model provided in CityScapes part.Did I misunderstand it?
Sincerely thanks!

**Comment by pengsida** [comment]
It is ok.
Maybe it is because that there is no detection result in the input image, which cause an interrupt.
I uploaded an cityscape image, and you could try it by `python run.py --type demo --cfg_file configs/city_rcnn_snake.yaml demo_path demo_images/berlin_000000_000019_leftImg8bit.png ct_score 0.3`.

**Comment by xiamingfu** [comment]
> It is ok.
> Maybe it is because that there is no detection result in the input image, which causes an interrupt.
> I uploaded a cityscape image, and you could try it by `python run.py --type demo --cfg_file configs/city_rcnn_snake.yaml demo_path demo_images/berlin_000000_000019_leftImg8bit.png ct_score 0.3`.

Yes,It works. It's just like you said exactly!!Changing an input iamge works effectively. Thanks a lot!
