### ISSUE TITLE
CT image +label  boundary image 作为输入如何实现？

### ISSUE THREAD

**Issue by Ruanyuzhe** [zju3dv/snake#49]
感谢作者优秀的工作！
最近受到deep snake的启发，想要将其应用到医学数据集中，用于血管的boundary detection。 然而由于数据集结构的不同，我的数据集并没有对应的json文件，并且没有对应的bbox的label。我的数据集所拥有的只有原CTimage 与 所对应的血管内外壁 boundary 的mask。 自己想通过修改作者的代码把数据集移植进去但遇到了困难。 我观察到作者似乎是通过tools.convert_sbd 来对数据集进行处理的。
我想首先听听作者的意见，以及如果可以的话能否share一份处理不同数据集的demo呢？
感激不尽！

**Comment by pengsida** [comment]
你可以给我几张示例图，我给你写个convert代码。

**Comment by RonDen** [comment]
可以考虑转换成COCO格式

**Comment by Ruanyuzhe** [comment]
<img width="114" alt="屏幕快照 2020-06-03 00 27 44" src="https://user-images.githubusercontent.com/56424269/83538938-67b33600-a531-11ea-94b9-c705da835a70.png">
<img width="147" alt="屏幕快照 2020-06-03 00 29 07" src="https://user-images.githubusercontent.com/56424269/83538944-697cf980-a531-11ea-91ad-d2019c5af8df.png">
由于数据集的特殊性，我只能从已有的论文上给你截图数据的demo，inputCT数据大小为[15,96,96]是3d输入，对应label的形状为[96,96]为通过0，1，2来标记不同的类别的mask。

**Comment by pengsida** [comment]
这个是label图片吗
![image](https://user-images.githubusercontent.com/11582122/83583742-c00d2680-a577-11ea-8af6-1a7060941ee2.png)

**Comment by Ruanyuzhe** [comment]
是的

**Comment by pengsida** [comment]
将已有轮廓存起来就好了，把这行代码替换掉：https://github.com/zju3dv/snake/blob/master/tools/convert_sbd.py#L93

**Comment by Ruanyuzhe** [comment]
txt的内容是什么样子的呀？我也在看这个代码，txt文件是需要根据数据集手动制作的吗？能不能给一个sbd数据集的txt的sample呀？

**Comment by pengsida** [comment]
1. 是的，把mask转成有序的坐标序列，也就是polygon。
2. 你下载SBD就可以知道txt的内容。

**Comment by Ruanyuzhe** [comment]
作者你好，我还有一个问题。在生成annotation时，用到了“area”,这个分割的面积对网络训练有影响吗，能否去掉？（因为我的label只有轮廓没有填充）

**Comment by pengsida** [comment]
对coco evaluation有影响。
如果你有polygon，算area应该挺简单的。

**Comment by xiemomoioio** [comment]
神仙作者，你也太好了 ^_^
