### ISSUE TITLE
About the Performance on COCO

### ISSUE THREAD

**Issue by lkevinzc** [zju3dv/snake#5]
Hi Authors!

Thanks for the nice work! Waiting for the code to play with it~

Just a quick question: did you try the model on COCO dataset and whether it can perform well on that much more challenging dataset as well?

**Comment by pengsida** [comment]
Yes. I directly appended it to the reppoints detector and only got 31.3 AP with an R-50-FPN backbone.
I have been searching a good way to train our network on coco.

**Comment by lkevinzc** [comment]
> Yes. I directly appended it to the reppoints detector and only got 31.3 AP with an R-50-FPN backbone.
> I have been searching a good way to train our network on coco.

Thank you for your reply! I see, looking forward to new ideas! ;)
