### ISSUE TITLE
torch.nn.parallel   RuntimeError

### ISSUE THREAD

**Issue by IcereamC** [zju3dv/snake#52]
你好，我一直在sbd数据集上训练一切都正常。最近试了一下pascalvoc2012数据集，转成coco格式之后训练出现以下问题：

![20200604144221](https://user-images.githubusercontent.com/39287994/83724182-689fb100-a672-11ea-8190-bb0a51458b5a.png)

训练命令 按照 #32修改

Ubuntu 16.04
torch1.1.0
cuda 10.2

**Comment by pengsida** [comment]
1. Pascal voc数据集的物体的mask内部有洞，在voc上训练效果不好，所以我们在SBD上训练。
2. 这个报错是因为数据为空，导致DataParallel()报错。你可以检查dataset返回的数据内容。

**Comment by IcereamC** [comment]
你说得对，我检查了coco格式的mask，的确惨不忍睹。
十分感谢！
