### ISSUE TITLE
extreme_utils build_ext  error

### ISSUE THREAD

**Issue by zoearthmoon** [zju3dv/snake#53]
hello
when i use

cd ../**extreme_utils**
python setup.py build_ext --inplace
it will show error

`creating C:\Users\T34808\Desktop\snake\lib\csrc\extreme_utils\build\lib.win-amd64-3.7
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Python37\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib/x64" /LIBPATH:C:\Python37\libs /LIBPATH:C:\Python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" cudart.lib c10.lib c10_cuda.lib torch.lib torch_python.lib _C.lib /EXPORT:PyInit__ext build\temp.win-amd64-3.7\Release\Users\T34808\Desktop\snake\lib\csrc\extreme_utils\utils.obj build\temp.win-amd64-3.7\Release\Users\T34808\Desktop\snake\lib\csrc\extreme_utils\src\nms.obj build\temp.win-amd64-3.7\Release\Users\T34808\Desktop\snake\lib\csrc\extreme_utils\src\utils.obj /OUT:build\lib.win-amd64-3.7\_ext.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\Users\T34808\Desktop\snake\lib\csrc\extreme_utils\_ext.cp37-win_amd64.lib
   正在建立程式庫 build\temp.win-amd64-3.7\Release\Users\T34808\Desktop\snake\lib\csrc\extreme_utils\_ext.cp37-win_amd64.lib 和物件 build\temp.win-amd64-3.7\Release\Users\T34808\Desktop\snake\lib\csrc\extreme_utils\_ext.cp37-win_amd64.exp
utils.obj : error LNK2001: 無法解析的外部符號 "public: long * __cdecl at::Tensor::data_ptr<long>(void)const " (??$data_ptr@J@Tensor@at@@QEBAPEAJXZ)
build\lib.win-amd64-3.7\_ext.cp37-win_amd64.pyd : fatal error LNK1120: 1 個無法解析的外部符號
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120`

i am use pytorch 1.4 + cu10.1 + windows
please help~
thank you~

**Comment by pengsida** [comment]
I don't know how to build the code on windows.
I recommend you to use Ubuntu 16.04.

**Comment by zoearthmoon** [comment]
hello @pengsida , i have slove this problem... i found that error is cause by 
`
at::Tensor.contiguous().data<long>
`
so i try to change long to int 
and .... it work~
i am not family with C
but i see some C teaching page say the long type and int type is the same range
so ... maybe someone can try this way

**Comment by pengsida** [comment]
Cool. I get it.

**Comment by weisq2691** [comment]
> hello @pengsida , i have slove this problem... i found that error is cause by
> `at::Tensor.contiguous().data<long>`
> so i try to change long to int
> and .... it work~
> i am not family with C
> but i see some C teaching page say the long type and int type is the same range
> so ... maybe someone can try this way

hello @zoearthmoon , i installed the code in the windows environment and encountered a problem similar to yours, can you please help me take a look?
`D:/Program Files/Anaconda3/envs/py36/lib/site-packages/torch/include\THC/THCNumerics.cuh(190): error: more than one operator "<" matches these operands:
            built-in operator "arithmetic < arithmetic"
            function "operator<(const __half &, const __half &)"
            operand types are: c10::Half < c10::Half

D:/Program Files/Anaconda3/envs/py36/lib/site-packages/torch/include\THC/THCNumerics.cuh(191): error: more than one operator "<=" matches these operands:
            built-in operator "arithmetic <= arithmetic"
            function "operator<=(const __half &, const __half &)"
            operand types are: c10::Half <= c10::Half

D:/Program Files/Anaconda3/envs/py36/lib/site-packages/torch/include\THC/THCNumerics.cuh(192): error: more than one operator ">" matches these operands:
            built-in operator "arithmetic > arithmetic"
            function "operator>(const __half &, const __half &)"
            operand types are: c10::Half > c10::Half

D:/Program Files/Anaconda3/envs/py36/lib/site-packages/torch/include\THC/THCNumerics.cuh(193): error: more than one operator ">=" matches these operands:
            built-in operator "arithmetic >= arithmetic"
            function "operator>=(const __half &, const __half &)"
            operand types are: c10::Half >= c10::Half

D:/Program Files/Anaconda3/envs/py36/lib/site-packages/torch/include\THC/THCNumerics.cuh(194): error: more than one operator "==" matches these operands:
            built-in operator "arithmetic == arithmetic"
            function "operator==(const __half &, const __half &)"
            operand types are: c10::Half == c10::Half

D:/Program Files/Anaconda3/envs/py36/lib/site-packages/torch/include\THC/THCNumerics.cuh(196): error: more than one operator "!=" matches these operands:
            built-in operator "arithmetic != arithmetic"
            function "operator!=(const __half &, const __half &)"
            operand types are: c10::Half != c10::Half

6 errors detected in the compilation of "C:/Users/pc/AppData/Local/Temp/tmpxft_0000731c_00000000-8_utils.cpp4.ii".
utils.cu
D:\Program Files\Anaconda3\envs\py36\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
error: command 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\\v9.0\\bin\\nvcc.exe' failed with exit status 2
`
thanks

**Comment by zoearthmoon** [comment]
@weisq2691 hello~
i found the compiler error is not base no linux or windows 
i think it always cause by program version error
i see your error message
i think that error is by torch version and cuda version not match
i hope that will help you

**Comment by yudadabing** [comment]
> at::Tensor.contiguous().data<long>
 I want to know which file is  at::Tensor.contiguous().data<long>  in?

**Comment by yudadabing** [comment]
hello @zoearthmoon , i have the same problem,so I want to know which file is at::Tensor.contiguous().data in?

**Comment by pengsida** [comment]
https://github.com/zju3dv/snake/blob/master/lib/csrc/extreme_utils/src/utils.cu#L199

**Comment by huangzy97** [comment]
> hello @pengsida , i have slove this problem... i found that error is cause by
> `at::Tensor.contiguous().data<long>`
> so i try to change long to int
> and .... it work~
> i am not family with C
> but i see some C teaching page say the long type and int type is the same range
> so ... maybe someone can try this way

I can not find the error messages about at::Tensor.contiguous().data<long> in file [](https://github.com/zju3dv/snake/blob/master/lib/csrc/extreme_utils/src/utils.cu),can you tell me where is it? thanks

**Comment by pengsida** [comment]
Like this: https://github.com/zju3dv/snake/blob/master/lib/csrc/extreme_utils/src/utils.cu#L292

**Comment by huangzy97** [comment]
> i have slove this problem

I replaced all the long in the file with int and succeeded, but later when I run demo.ipynb, I got an error again, I don't know if you met it or not, the error is as follow:
WARNING: NO MODEL LOADED !!!
  0%|                                                                                            | 0/1 [00:01<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-3c5f1c6c672e> in <module>
      1 from run import run_demo
----> 2 run_demo()

D:\image segmentation\snake-master\run.py in run_demo()
     93 def run_demo():
     94     from tools import demo
---> 95     demo.demo()
     96 
     97 

D:\image segmentation\snake-master\tools\demo.py in demo()
     66         batch['inp'] = torch.FloatTensor(batch['inp'])[None].cuda()
     67         with torch.no_grad():
---> 68             output = network(batch['inp'], batch)
     69         visualizer.visualize(output, batch)

D:\soft\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

D:\image segmentation\snake-master\lib\networks\snake\ct_snake.py in forward(self, x, batch)
     57         if cfg.use_gt_det:
     58             self.use_gt_detection(output, batch)
---> 59         output = self.gcn(output, cnn_feature, batch)
     60         return output
     61 

D:\soft\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

D:\image segmentation\snake-master\lib\networks\snake\evolve.py in forward(self, output, cnn_feature, batch)
    104         if not self.training:
    105             with torch.no_grad():
--> 106                 init = self.prepare_testing_init(output)
    107                 ex = self.init_poly(self.init_gcn, cnn_feature, init['i_it_4py'], init['c_it_4py'], init['ind'])
    108                 ret.update({'ex': ex})

D:\image segmentation\snake-master\lib\networks\snake\evolve.py in prepare_testing_init(self, output)
     37 
     38     def prepare_testing_init(self, output):
---> 39         init = snake_gcn_utils.prepare_testing_init(output['detection'][..., :4], output['detection'][..., 4])
     40         output['detection'] = output['detection'][output['detection'][..., 4] > snake_config.ct_score]
     41         output.update({'it_ex': init['i_it_4py']})

D:\image segmentation\snake-master\lib\utils\snake\snake_gcn_utils.py in prepare_testing_init(box, score)
     28 def prepare_testing_init(box, score):
     29     i_it_4pys = snake_decode.get_init(box)
---> 30     i_it_4pys = uniform_upsample(i_it_4pys, snake_config.init_poly_num)
     31     c_it_4pys = img_poly_to_can_poly(i_it_4pys)
     32 

D:\image segmentation\snake-master\lib\utils\snake\snake_gcn_utils.py in uniform_upsample(poly, p_num)
    224     edge_num_sum = torch.sum(edge_num, dim=2)
    225     edge_idx_sort = torch.argsort(edge_num, dim=2, descending=True)
--> 226     extreme_utils.calculate_edge_num(edge_num, edge_num_sum, edge_idx_sort, p_num)
    227     edge_num_sum = torch.sum(edge_num, dim=2)
    228     assert torch.all(edge_num_sum == p_num)

**RuntimeError: expected scalar type Int but found Long (data at D:/soft/Anaconda3/envs/pytorch/lib/site-packages/torch/include\ATen/core/TensorMethods.h:1821)
(no backtrace available)**
thanks

**Comment by pengsida** [comment]
Did you recompile the code?

**Comment by neiheih** [comment]
> > i have slove this problem
> 
> ## I replaced all the long in the file with int and succeeded, but later when I run demo.ipynb, I got an error again, I don't know if you met it or not, the error is as follow:
> WARNING: NO MODEL LOADED !!!
> 0%| | 0/1 [00:01<?, ?it/s]
> RuntimeError Traceback (most recent call last)
> in
> 1 from run import run_demo
> ----> 2 run_demo()
> 
> D:\image segmentation\snake-master\run.py in run_demo()
> 93 def run_demo():
> 94 from tools import demo
> ---> 95 demo.demo()
> 96
> 97
> 
> D:\image segmentation\snake-master\tools\demo.py in demo()
> 66 batch['inp'] = torch.FloatTensor(batch['inp'])[None].cuda()
> 67 with torch.no_grad():
> ---> 68 output = network(batch['inp'], batch)
> 69 visualizer.visualize(output, batch)
> 
> D:\soft\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in **call**(self, *input, **kwargs)
> 545 result = self._slow_forward(*input, **kwargs)
> 546 else:
> --> 547 result = self.forward(*input, **kwargs)
> 548 for hook in self._forward_hooks.values():
> 549 hook_result = hook(self, input, result)
> 
> D:\image segmentation\snake-master\lib\networks\snake\ct_snake.py in forward(self, x, batch)
> 57 if cfg.use_gt_det:
> 58 self.use_gt_detection(output, batch)
> ---> 59 output = self.gcn(output, cnn_feature, batch)
> 60 return output
> 61
> 
> D:\soft\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in **call**(self, *input, **kwargs)
> 545 result = self._slow_forward(*input, **kwargs)
> 546 else:
> --> 547 result = self.forward(*input, **kwargs)
> 548 for hook in self._forward_hooks.values():
> 549 hook_result = hook(self, input, result)
> 
> D:\image segmentation\snake-master\lib\networks\snake\evolve.py in forward(self, output, cnn_feature, batch)
> 104 if not self.training:
> 105 with torch.no_grad():
> --> 106 init = self.prepare_testing_init(output)
> 107 ex = self.init_poly(self.init_gcn, cnn_feature, init['i_it_4py'], init['c_it_4py'], init['ind'])
> 108 ret.update({'ex': ex})
> 
> D:\image segmentation\snake-master\lib\networks\snake\evolve.py in prepare_testing_init(self, output)
> 37
> 38 def prepare_testing_init(self, output):
> ---> 39 init = snake_gcn_utils.prepare_testing_init(output['detection'][..., :4], output['detection'][..., 4])
> 40 output['detection'] = output['detection'][output['detection'][..., 4] > snake_config.ct_score]
> 41 output.update({'it_ex': init['i_it_4py']})
> 
> D:\image segmentation\snake-master\lib\utils\snake\snake_gcn_utils.py in prepare_testing_init(box, score)
> 28 def prepare_testing_init(box, score):
> 29 i_it_4pys = snake_decode.get_init(box)
> ---> 30 i_it_4pys = uniform_upsample(i_it_4pys, snake_config.init_poly_num)
> 31 c_it_4pys = img_poly_to_can_poly(i_it_4pys)
> 32
> 
> D:\image segmentation\snake-master\lib\utils\snake\snake_gcn_utils.py in uniform_upsample(poly, p_num)
> 224 edge_num_sum = torch.sum(edge_num, dim=2)
> 225 edge_idx_sort = torch.argsort(edge_num, dim=2, descending=True)
> --> 226 extreme_utils.calculate_edge_num(edge_num, edge_num_sum, edge_idx_sort, p_num)
> 227 edge_num_sum = torch.sum(edge_num, dim=2)
> 228 assert torch.all(edge_num_sum == p_num)
> 
> **RuntimeError: expected scalar type Int but found Long (data at D:/soft/Anaconda3/envs/pytorch/lib/site-packages/torch/include\ATen/core/TensorMethods.h:1821) (no backtrace available)**
> thanks


> > i have slove this problem
> 
> ## I replaced all the long in the file with int and succeeded, but later when I run demo.ipynb, I got an error again, I don't know if you met it or not, the error is as follow:
> WARNING: NO MODEL LOADED !!!
> 0%| | 0/1 [00:01<?, ?it/s]
> RuntimeError Traceback (most recent call last)
> in
> 1 from run import run_demo
> ----> 2 run_demo()
> 
> D:\image segmentation\snake-master\run.py in run_demo()
> 93 def run_demo():
> 94 from tools import demo
> ---> 95 demo.demo()
> 96
> 97
> 
> D:\image segmentation\snake-master\tools\demo.py in demo()
> 66 batch['inp'] = torch.FloatTensor(batch['inp'])[None].cuda()
> 67 with torch.no_grad():
> ---> 68 output = network(batch['inp'], batch)
> 69 visualizer.visualize(output, batch)
> 
> D:\soft\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in **call**(self, *input, **kwargs)
> 545 result = self._slow_forward(*input, **kwargs)
> 546 else:
> --> 547 result = self.forward(*input, **kwargs)
> 548 for hook in self._forward_hooks.values():
> 549 hook_result = hook(self, input, result)
> 
> D:\image segmentation\snake-master\lib\networks\snake\ct_snake.py in forward(self, x, batch)
> 57 if cfg.use_gt_det:
> 58 self.use_gt_detection(output, batch)
> ---> 59 output = self.gcn(output, cnn_feature, batch)
> 60 return output
> 61
> 
> D:\soft\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py in **call**(self, *input, **kwargs)
> 545 result = self._slow_forward(*input, **kwargs)
> 546 else:
> --> 547 result = self.forward(*input, **kwargs)
> 548 for hook in self._forward_hooks.values():
> 549 hook_result = hook(self, input, result)
> 
> D:\image segmentation\snake-master\lib\networks\snake\evolve.py in forward(self, output, cnn_feature, batch)
> 104 if not self.training:
> 105 with torch.no_grad():
> --> 106 init = self.prepare_testing_init(output)
> 107 ex = self.init_poly(self.init_gcn, cnn_feature, init['i_it_4py'], init['c_it_4py'], init['ind'])
> 108 ret.update({'ex': ex})
> 
> D:\image segmentation\snake-master\lib\networks\snake\evolve.py in prepare_testing_init(self, output)
> 37
> 38 def prepare_testing_init(self, output):
> ---> 39 init = snake_gcn_utils.prepare_testing_init(output['detection'][..., :4], output['detection'][..., 4])
> 40 output['detection'] = output['detection'][output['detection'][..., 4] > snake_config.ct_score]
> 41 output.update({'it_ex': init['i_it_4py']})
> 
> D:\image segmentation\snake-master\lib\utils\snake\snake_gcn_utils.py in prepare_testing_init(box, score)
> 28 def prepare_testing_init(box, score):
> 29 i_it_4pys = snake_decode.get_init(box)
> ---> 30 i_it_4pys = uniform_upsample(i_it_4pys, snake_config.init_poly_num)
> 31 c_it_4pys = img_poly_to_can_poly(i_it_4pys)
> 32
> 
> D:\image segmentation\snake-master\lib\utils\snake\snake_gcn_utils.py in uniform_upsample(poly, p_num)
> 224 edge_num_sum = torch.sum(edge_num, dim=2)
> 225 edge_idx_sort = torch.argsort(edge_num, dim=2, descending=True)
> --> 226 extreme_utils.calculate_edge_num(edge_num, edge_num_sum, edge_idx_sort, p_num)
> 227 edge_num_sum = torch.sum(edge_num, dim=2)
> 228 assert torch.all(edge_num_sum == p_num)
> 
> **RuntimeError: expected scalar type Int but found Long (data at D:/soft/Anaconda3/envs/pytorch/lib/site-packages/torch/include\ATen/core/TensorMethods.h:1821) (no backtrace available)**
> thanks

As mentioned in  https://github.com/pytorch/pytorch/issues/23056#issue-470124574
Just replace all the occurrences of longs in your code or the code you referenced with int64_t.
It works for me.

**Comment by LevinLittleDream** [comment]
3 errors detected in the compilation of "/media/disk/exp/snake-master/snake-master/lib/csrc/dcn_v2/src/cuda/dcn_v2_cuda.cu
这该怎么解决啊？
