### ISSUE TITLE
what is segmentation data mean?

### ISSUE THREAD

**Issue by zoearthmoon** [zju3dv/snake#54]
hello ~
i am not family with training data
can someone help me to explan the segmentation data mean?
i see there is two type data in json

`"segmentation": [[250.0, 253.5, 249.0, 253.5, 248.5, 253.0, 248.0, 252.5, 247.0, 252.5, 246.0, 252.5, 245.0,....... `

and 

`{"segmentation": {"size": [300, 400], "counts": "a^W12S99L5I40M3O1000O1000...............`

thank you very much~😊

**Comment by pengsida** [comment]
https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch

**Comment by zoearthmoon** [comment]
@pengsida thank you~😊

**Comment by zoearthmoon** [comment]
@pengsida hello~
i have see the page
and i still not understand 
`{"segmentation": {"size": [300, 400], "counts": "a^W12S99L5I40M3O1000O1000...............`
in the 
https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch
show the count format is like 100, 2,3.....
why the dataset counts is 
`a^W12S99L5I40M3O1000O1000......`
thank for your help~

**Comment by pengsida** [comment]
It is RLE annotation.
https://github.com/facebookresearch/Detectron/issues/100
