### ISSUE TITLE
For multi-components object evaluation.

### ISSUE THREAD

**Issue by LetsGoFir** [zju3dv/snake#56]
Thanks for your great work!

In 'lib/evaluators/cityscapes/rcnn_snake.py', you assign every poly a label 'i'. 
Then for multi-components objects, will them be different instances when evaluation?
I am fresh to evaluate the instance...
```
with open(txt_path, 'w') as f:
        for i in range(len(label)):
            instance_path = os.path.join(instance_dir, 'instance'+str(i)+'.png')
            cv2.imwrite(instance_path, mask[i])
            instance_path = os.path.join('../mask', img_id, 'instance'+str(i)+'.png')
            f.write('{} {} {}\n'.format(instance_path, label[i], score[i]))
```

**Comment by pengsida** [comment]
The fragments are merged into one mask before the label assignment: https://github.com/zju3dv/snake/blob/master/lib/evaluators/cityscapes/rcnn_snake.py#L39

**Comment by LetsGoFir** [comment]
Thanks for your prompt reply!
