### ISSUE TITLE
关于最终结果只有一个类别的输出

### ISSUE THREAD

**Issue by Ruanyuzhe** [zju3dv/snake#58]
作者您好，我之前也想您提过问题，我讲deep snake应用到了医学的数据集，然后来检测血管内壁和血管外壁，如果我没记错的话我用的是ro_34（Kins用的那个网络），但是我没有仔细去分析网络，然后我有三个问题：
1最终训练的可视化结果，要么只输出一个轮廓，要么就没有输出，我在想是不是阈值的问题，还是我网络训练错误了。
2.在训练的时候 ctscore=0.3是什么意思
3.我在想同时添加ground truth在同一张输出结果上，应该选择batch里面哪个key，自己选择了i_gt_py但比例完全不对。

**Comment by pengsida** [comment]
1. 你把detection分为了几类，如果只分为1类，很可能有问题。
2. ct_score是detection的阈值，具体可以看 https://arxiv.org/abs/1904.07850
3. 选 i_gt_py，比例要乘以4。具体变换可以看数据集 https://github.com/zju3dv/snake/blob/master/lib/datasets/kins/snake.py#L144
