### ISSUE TITLE
Error compiling objects for extension

### ISSUE THREAD

**Issue by AF2O** [zju3dv/snake#60]
您好，我在安装环境的时候遇到问题：
指令 python setup.py install --cuda_ext --cpp_ext
error：
RuntimeError: Error compiling objects for extension
(snake) [usr@localhost apex]$ Error compiling objects for extension

请问如何解决呢？
期待答复~

**Comment by pengsida** [comment]
这报错太简略了，我不知道具体原因。可以把错误消息都列出来。

**Comment by AF2O** [comment]
> 这报错太简略了，我不知道具体原因。可以把错误消息都列出来。
下面是报错信息：
(Snake) [caijt@localhost apex]$ python setup.py install --cuda_ext --cpp_ext
torch.__version__  =  1.5.1
which: no hipcc in (/usr/caijt/anaconda3/envs/Snake/bin:/usr/caijt/anaconda3/bin:/usr/caijt/anaconda3/bin:/usr/caijt/anaconda3/condabin:/usr/local/cuda-10.2/bin:/usr/caijt/anaconda3/bin:/usr/caijt/anaconda3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/caijt/.local/bin:/usr/caijt/bin)

Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
from /usr/local/cuda-10.2/bin

Pytorch binaries were compiled with Cuda 10.2

running install
running bdist_egg
running egg_info
writing apex.egg-info/PKG-INFO
writing dependency_links to apex.egg-info/dependency_links.txt
writing top-level names to apex.egg-info/top_level.txt
/usr/caijt/anaconda3/envs/Snake/lib/python3.7/site-packages/torch/utils/cpp_extension.py:305: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'apex.egg-info/SOURCES.txt'
writing manifest file 'apex.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'amp_C' extension
gcc -pthread -B /usr/caijt/anaconda3/envs/Snake/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/caijt/anaconda3/envs/Snake/lib/python3.7/site-packages/torch/include -I/usr/caijt/anaconda3/envs/Snake/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/usr/caijt/anaconda3/envs/Snake/lib/python3.7/site-packages/torch/include/TH -I/usr/caijt/anaconda3/envs/Snake/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/usr/caijt/anaconda3/envs/Snake/include/python3.7m -c csrc/amp_C_frontend.cpp -o build/temp.linux-x86_64-3.7/csrc/amp_C_frontend.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-10.2/bin/nvcc -I/usr/caijt/anaconda3/envs/Snake/lib/python3.7/site-packages/torch/include -I/usr/caijt/anaconda3/envs/Snake/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/usr/caijt/anaconda3/envs/Snake/lib/python3.7/site-packages/torch/include/TH -I/usr/caijt/anaconda3/envs/Snake/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/usr/caijt/anaconda3/envs/Snake/include/python3.7m -c csrc/multi_tensor_scale_kernel.cu -o build/temp.linux-x86_64-3.7/csrc/multi_tensor_scale_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -lineinfo -O3 --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
csrc/multi_tensor_apply.cuh(47): error: identifier "AT_CHECK" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00027ace_00000000-6_multi_tensor_scale_kernel.cpp1.ii".
error: command '/usr/local/cuda-10.2/bin/nvcc' failed with exit status 1

**Comment by pengsida** [comment]
这个是编译apex的时候报错了，你用的版本是`39e153a3159724432257a8fc118807b359f4d1c8`吗

**Comment by AF2O** [comment]
> 这个是编译apex的时候报错了，你用的版本是`39e153a3159724432257a8fc118807b359f4d1c8`吗

是的，没错，checkout过了

**Comment by pengsida** [comment]
把cuda换成9.0, pytorch换成1.1试试。

**Comment by AF2O** [comment]
> 把cuda换成9.0, pytorch换成1.1试试。

解决了，谢谢

**Comment by wangshuo2020** [comment]
> > 把cuda换成9.0, pytorch换成1.1试试。
> 
> 解决了，谢谢

你用的是什么版本的编译器 gcc5.5?
