### ISSUE TITLE
关于同时训练detector和snake

### ISSUE THREAD

**Issue by cherishtttz** [zju3dv/snake#61]
非常感谢作者的贡献，拜读了几遍论文，有一个疑问是，在同时训练detector和snake的时候，请问end-to-end的实现是指将检测的结果作为snake分割的输入，再通过最后的loss进行反向传播吗？那最后生成的是检测、分割两个模型还是一个模型呢？如果只训练snake，是不是就直接调用detector的模型先做检测，再将结果作为输入去训练？

**Comment by pengsida** [comment]
1. 检测、分割共用一个backbone。end-to-end的实现是指将gt bbox作为snake分割的输入，再通过最后的loss进行反向传播。
2. 如果只训练snake，可以直接调用detector的模型先做检测，再将结果作为输入去训练。

**Comment by cherishtttz** [comment]
@pengsida 好的，感谢~也就是说论文里多个Circonv层的输入应该是已经卷积过的feature map和得到的contour，而不是图像本身了吧？

**Comment by pengsida** [comment]
circonv层的输入是定义在contour上的一组features。
