### ISSUE TITLE
Cityscapes val AP is evaluated on 492 images instead of 500 images

### ISSUE THREAD

**Issue by bowenc0221** [zju3dv/snake#63]
Hi @pengsida,

Thanks for open-sourcing this code. I tried to run evaluation on Cityscapes val with the command: `python run.py --type evaluate --cfg_file configs/city_rcnn_snake.yaml test.dataset CityscapesVal`.

However, I found the the model was only evaluated on a subset of 492 images. I checked output files and found there missed 8 images from the city `lindau` (59 images to test but model only produced 51 outputs).

The way evaluator is written also only takes 492 images into account and I got 37.4 AP which is the same as the number in the paper.
<img width="363" alt="Screen Shot 2020-07-05 at 2 56 08 PM" src="https://user-images.githubusercontent.com/25308473/86543018-aab94e00-becf-11ea-81dc-b98626c91b99.png">

Could you help check what is wrong with the evaluation code?

Thanks.

**Comment by pengsida** [comment]
Some images do not contain the target classes of instance segmentation.
So I filter them out at here: https://github.com/zju3dv/snake/blob/master/lib/utils/snake/snake_cityscapes_utils.py#L68

**Comment by bowenc0221** [comment]
Could you tell me how to still save predictions for those images without instances? I feel it is not fair to remove those images from evaluation, because false positives are also penalized in calculating AP.

**Comment by pengsida** [comment]
Remove this line https://github.com/zju3dv/snake/blob/master/lib/utils/snake/snake_cityscapes_utils.py#L78
I a

**Comment by bowenc0221** [comment]
Thanks, I tried evaluating on 500 images and still got 37.4% AP.
