### ISSUE TITLE
对于output有一些不解

### ISSUE THREAD

**Issue by Ruanyuzhe** [zju3dv/snake#64]
作者您好，我在移植您代码到医疗图像的过程中对于输出的量有一些不解：
    def evaluate(self, output, batch):
        detection = output['detection']
        score = detection[:, 4].detach().cpu().numpy()
        label = detection[:, 5].detach().cpu().numpy().astype(int)
        py = output['py'][-1].detach().cpu().numpy() * snake_config.down_ratio
由于我需要对结果进行IOU或者Hausdorff distance的计算，在这个detection的key中我输出了label与detection同时进行观察。却发现结果和我理解的有些不一致，能否解释一下output中detection key包含了什么？以下是detection的sample：
detection: tensor([[17.1544, 18.0598, 28.8456, 29.9402,  0.8509,  1.0000],
        [17.1544, 18.0598, 28.8456, 29.9402,  0.8111,  0.0000]],
       device='cuda:0')
label: [1 0]

其中的label又是代表什么？

**Comment by pengsida** [comment]
detection: [x_min, y_min, x_max, y_max, score, label]
label: 物体类别

**Comment by Ruanyuzhe** [comment]
那其中score的分数越高是代表此时这个detection越有可能是属于label的的意思吗

**Comment by pengsida** [comment]
是的

**Comment by qq414256215** [comment]
> 
> 
> 作者您好，我在移植您代码到医疗图像的过程中对于输出的量有一些不解：
> def evaluate(self, output, batch):
> detection = output['detection']
> score = detection[:, 4].detach().cpu().numpy()
> label = detection[:, 5].detach().cpu().numpy().astype(int)
> py = output['py'][-1].detach().cpu().numpy() * snake_config.down_ratio
> 由于我需要对结果进行IOU或者Hausdorff distance的计算，在这个detection的key中我输出了label与detection同时进行观察。却发现结果和我理解的有些不一致，能否解释一下output中detection key包含了什么？以下是detection的sample：
> detection: tensor([[17.1544, 18.0598, 28.8456, 29.9402, 0.8509, 1.0000],
> [17.1544, 18.0598, 28.8456, 29.9402, 0.8111, 0.0000]],
> device='cuda:0')
> label: [1 0]
> 
> 其中的label又是代表什么？

请问这个项目是在Windows下面跑的还是ubuntu系统上面跑起来的。怎么感觉有的命令不是Windows系统的？

**Comment by pengsida** [comment]
这个代码在windows和ubuntu上应该都可以跑。
我没在windows上跑过。

**Comment by qq414256215** [comment]
请问一下是直接可以跑起来还是需要修改配置才可以跑？谢谢


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月14日 15:57，pengsida<notifications@github.com> 写道：

这个代码在windows和ubuntu上应该都可以跑。
我没在windows上跑过。

**Comment by pengsida** [comment]
我没跑过。

**Comment by qq414256215** [comment]
> 
> 
> > 作者您好，我在移植您代码到医疗图像的过程中对于输出的量有一些不解：
> > def evaluate(self, output, batch):
> > detection = output['detection']
> > score = detection[:, 4].detach().cpu().numpy()
> > label = detection[:, 5].detach().cpu().numpy().astype(int)
> > py = output['py'][-1].detach().cpu().numpy() * snake_config.down_ratio
> > 由于我需要对结果进行IOU或者Hausdorff distance的计算，在这个detection的key中我输出了label与detection同时进行观察。却发现结果和我理解的有些不一致，能否解释一下output中detection key包含了什么？以下是detection的sample：
> > detection: tensor([[17.1544, 18.0598, 28.8456, 29.9402, 0.8509, 1.0000],
> > [17.1544, 18.0598, 28.8456, 29.9402, 0.8111, 0.0000]],
> > device='cuda:0')
> > label: [1 0]
> > 其中的label又是代表什么？
> 
> 请问这个项目是在Windows下面跑的还是ubuntu系统上面跑起来的。怎么感觉有的命令不是Windows系统的？
请问一下是直接可以跑起来还是需要需改部分的配置文件，目前我用的是Windows，但是没有跑起来。他需要的是什么样子的环境readme里面没有详细的说明。我看了一下“ snake/INSTALL.md ”这个，但是里面有的代码看不懂

**Comment by qq414256215** [comment]
你没跑过怎么知道在Windows下面可以跑呀？




祝好运~


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月14日 16:03，pengsida<notifications@github.com> 写道：

我没跑过。

**Comment by pengsida** [comment]
有人跑过。

**Comment by qq414256215** [comment]
你也是在学习这个么？想跑起来吗?


我想把它跑起来，可以微信聊呀.


微信：18811132113


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月14日 16:06，pengsida<notifications@github.com> 写道：

有人跑过。

**Comment by pengsida** [comment]
我是作者。

**Comment by qq414256215** [comment]
您好，
您是作者为啥不跑起来呢？


可以帮我跑起来吗？


有偿，有些我看不懂


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月14日 16:08，pengsida<notifications@github.com> 写道：

我是作者。

**Comment by pengsida** [comment]
我没有windows系统，在ubuntu上可以跑。

**Comment by qq414256215** [comment]
我把电脑换成ubuntu系统，您愿意帮我远程跑一下吗？




我想把它跑起来，然后修改源代码，发个论文求毕业呀


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月14日 16:11，pengsida<notifications@github.com> 写道：

我没有windows系统，在ubuntu上可以跑。

**Comment by Ruanyuzhe** [comment]
作者你好，非常抱歉频繁的问您问题。我将deep snake 应用于医疗数据，在evaluate的时候有一些问题，我总结了一下。
1.rles：snake_eval_utils.coco_poly_to_rle中的rle是代表什么？
2.我将coco_det的sample输出出来如下：
coco_dets: [{'image_id': 2976, 'category_id': 1, 'segmentation': {'size': [96, 96], 'counts': '_n25h27J4M2N2N2O1N1O2O0O2O0O2O00000000000001N10001N101N2N2N3M4KeW3'}, 'score': 0.93}, {'image_id': 2976, 'category_id': 2, 'segmentation': {'size': [96, 96], 'counts': '_n25h27J4M2N2N2O1N1O2O0O2O0O2O00000000000001N10001N101N2N2N3M4KeW3'}, 'score': 0.86}, {'image_id': 2976, 'category_id': 1, 'segmentation': {'size': [96, 96], 'counts': '\\W37g25K4L3N2N2N2O1N2O001N10001O0000000001O0O101O0O2O1N1O3M2N2M5K5Jdh2'}, 'score': 0.37}]

其中有很多乱码这是代表什么意思？
3.我想计算结果的Hausdorff distance, 需要用到输出的poly以及gt的poly，其中gt的poly我并没有在代码中看到调用，我应该在哪里调用gt的poly？
4.我看到在evaluate中，对output的poly有做affine的变化，这个gt的poly需要做变化吗？

**Comment by pengsida** [comment]
1. 第一个问题和第二个问题：https://github.com/zju3dv/snake/issues/54
2. `output['i_gt_py']`是gt的poly: https://github.com/zju3dv/snake/blob/master/lib/train/trainers/snake.py#L43
3. 做affine变化把output的poly变换回原图。你说的给gt poly做变化是为了做什么？

**Comment by qq414256215** [comment]
您好




请问您是浙大这边的吗？


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月15日 10:33，pengsida<notifications@github.com> 写道：

第一个问题和第二个问题：#54
output['i_gt_py']是gt的poly: https://github.com/zju3dv/snake/blob/master/lib/train/trainers/snake.py#L43
做affine变化把output的poly变换回原图。你说的给gt poly做变化是为了做什么？

**Comment by Ruanyuzhe** [comment]
def evaluate(self, output, batch):
        detection = output['detection']
        score = detection[:, 4].detach().cpu().numpy()
        label = detection[:, 5].detach().cpu().numpy().astype(int)
        py = output['py'][-1].detach().cpu().numpy() * snake_config.down_ratio

        print("gt_poly:",output["i_gt_py"])


作者您好，尝试输出output['i_gt_py']却没有这个key。我也没有更改其中的结构，我输出了一下output所有的key：
        # ct_hm
        # wh
        # ct
        # detection
        # it_ex
        # ex
        # it_py
        # py
只有这些key。

**Comment by pengsida** [comment]
> 您好 请问您是浙大这边的吗？ | | 袁建野 | | aku_cintapadamu@163.com | 签名由网易邮箱大师定制 在2020年7月15日 10:33，pengsida<notifications@github.com> 写道： 第一个问题和第二个问题：#54 output['i_gt_py']是gt的poly: https://github.com/zju3dv/snake/blob/master/lib/train/trainers/snake.py#L43 做affine变化把output的poly变换回原图。你说的给gt poly做变化是为了做什么？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是的

**Comment by pengsida** [comment]
`batch`中有`i_gt_py`，但不是原图的，需要变换回原图。

**Comment by Ruanyuzhe** [comment]
batch 中的i_gt_py是需要和py同样的处理吗：
py = output['py'][-1].detach().cpu().numpy() * snake_config.down_ratio
img_id = int(batch['meta']['img_id'][0])
center = batch['meta']['center'][0].detach().cpu().numpy()
scale = batch['meta']['scale'][0].detach().cpu().numpy()
h, w = batch['inp'].size(2), batch['inp'].size(3)
trans_output_inv = data_utils.get_affine_transform(center, scale, 0, [w, h], inv=1)
img = self.coco.loadImgs(img_id)[0]
ori_h, ori_w = img['height'], img['width']
py = [data_utils.affine_transform(py_, trans_output_inv) for py_ in py]

**Comment by pengsida** [comment]
对的，需要做仿射变换。

**Comment by Ruanyuzhe** [comment]
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.198
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.614
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.079
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.161
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.298
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.280
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.321
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.321
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.304
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.416
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 作者你好我想问一问这个evaluation最后的结果分别代表什么，我仔细读了读论文还是没搞明白

**Comment by pengsida** [comment]
这是coco ap metric。

**Comment by qq414256215** [comment]
请问一下我配置到了“         git checkout 39e153a3159724432257a8fc118807b359f4d1c8”这一步的时候报错：error: Your local changes to the following files would be overwritten by checkout:
        .gitmodules
        README.md
        apex/__init__.py
        apex/amp/README.md
        apex/amp/__init__.py
        apex/amp/_amp_state.py
        apex/amp/_initialize.py
        apex/amp/_process_optimizer.py
        apex/amp/compat.py
        apex/amp/frontend.py
        apex/amp/handle.py
        apex/amp/lists/functional_overrides.py
        apex/amp/lists/tensor_overrides.py
        apex/amp/lists/torch_overrides.py
        apex/amp/scaler.py
        apex/amp/utils.py
        apex/contrib/csrc/groupbn/batch_norm.cu
        apex/contrib/csrc/groupbn/batch_norm.h
        apex/contrib/csrc/groupbn/batch_norm_add_relu.cu
        apex/contrib/csrc/groupbn/batch_norm_add_relu.h
        apex/contrib/csrc/groupbn/cuda_utils.h
        apex/contrib/csrc/groupbn/interface.cpp
        apex/contrib/csrc/groupbn/ipc.cu
        apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h
        apex/contrib/csrc/multihead_attn/additive_masked_softmax_dropout.cpp
        apex/contrib/csrc/multihead_attn/additive_masked_softmax_dropout_cuda.cu
        apex/contrib/csrc/multihead_attn/dropout.h
        apex/contrib/csrc/multihead_attn/encdec_multihead_attn.cpp
        apex/contrib/csrc/multihead_attn/encdec_multihead_attn_cuda.cu
        apex/contrib/csrc/multihead_attn/encdec_multihead_attn_norm_add.cpp
        apex/contrib/csrc/multihead_attn/encdec_multihead_attn_norm_add_cuda.cu
        apex/contrib/csrc/multihead_attn/layer_norm.h
        apex/contrib/csrc/multihead_attn/masked_softmax_dropout.cpp
        apex/contrib/csrc/multihead_attn/masked_softmax_dropout_cuda.cu
        apex/contrib/csrc/multihead_attn/self_multihead_attn.cpp
        apex/contrib/csrc/multihead_attn/self_multihead_attn_bias.cpp
        apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_additive_mask.cpp
        apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_additive_mask_cuda.cu
        apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_cuda.cu
        apex/contrib/csrc/multihead_attn/self_multihead_attn_cuda.cu
        apex/contrib/csrc/multihead_attn/self_multihead_attn_norm_add.cpp
        apex/contrib/csrc/multihead_attn/self_multihead_attn_norm_add_cuda.cu
        apex/contrib/csrc/multihead_attn/softmax.h
        apex/contrib/csrc/multihead_attn/strided_batched_gemm.h
        apex/contrib/csrc/optimizers/fused_adam_cuda.cpp
        apex/contrib/csrc/optimizers/fused_adam_cuda_kernel.cu
        apex/contrib/csrc/optimizers/fused_lamb_cuda.cpp
        apex/contrib/csrc/optimizers/fused_lamb_cuda_kernel.cu
        apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb.cpp
        apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb_kernel.cu
        apex/contrib/csrc/xentropy/interface.cpp
        apex/contrib/csrc/xentropy/xentropy_kernel.cu
        apex/contrib/examples/multihead_attn/func_test_multihead_attn.py
        apex/contrib/examples/multihead_attn/perf_test_multihead_attn.py
        apex/contrib/groupbn/__init__.py
        apex/contrib/groupbn/batch_norm.py
        apex/contrib/multihead_attn/README.md
        apex/contrib/multihead_attn/__init__.py
        apex/contrib/multihead_attn/encdec_multihead_attn.py
        apex/contrib/multihead_attn/encdec_multihead_attn_func.py
        apex/contrib/multihead_attn/fast_encdec_multihead_attn_func.py
        apex/contrib/multihead_attn/fast_encdec_multihead_attn_norm_add_func.py
        apex/contrib/multihead_attn/fast_self_multihead_attn_func.py
        apex/contrib/multihead_attn/fast_self_multihead_attn_norm_add_func.py
        apex/contrib/multihead_attn/mask_softmax_dropout_func.py
        apex/contrib/multihead_attn/self_multihead_attn.py
        apex/contrib/multihead_attn/self_multihead_attn_func.py
        apex/contrib/optimizers/__init__.py
        apex/contrib/optimizers/distributed_fused_adam.py
        apex/contrib/optimizers/distributed_fused_adam_v2.py
        apex/contrib/optimizers/distributed_fused_adam_v3.py
        apex/contrib/optimizers/distributed_fused_lamb.py
        apex/contrib/optimizers/fp16_optimizer.py
        apex/contrib/optimizers/fused_adam.py
        apex/contrib/optimizers/fused_lamb.py
        apex/contrib/optimizers/fused_sgd.py
        apex/contrib/sparsity/__init__.py
        apex/contrib/sparsity/asp.py
        apex/contrib/sparsity/sparse_masklib.py
        apex/contrib/sparsity/test/checkpointing_test_part1.py
        apex/contrib/sparsity/test/checkpointing_test_part2.py
        apex/contrib/sparsity/test/checkpointing_test_reference.py
        apex/contrib/sparsity/test/toy_problem.py
        apex/contrib/test/multihead_attn/test_encdec_multihead_attn.py
        apex/contrib/test/multihead_attn/test_encdec_multihead_attn_norm_add.py
        apex/contrib/test/multihead_attn/test_mha_fused_softmax.py
        apex/contrib/test/multihead_attn/test_self_multihead_attn.py
        apex/contrib/test/multihead_attn/test_self_multihead_attn_norm_add.py
        apex/contrib/test/test_label_smoothing.py
        apex/contrib/xentropy/__init__.py
        apex/contrib/xentropy/softmax_xentropy.py
        apex/mlp/__init__.py
        apex/mlp/mlp.py
        apex/normalization/fused_layer_norm.py
        apex/optimizers/__init__.py
        apex/optimizers/fused_adagrad.py
        apex/optimizers/fused_adam.py
        apex/optimizers/fused_lamb.py
        apex/optimizers/fused_novograd.py
        apex/optimizers/fused_sgd.py
        apex/parallel/LARC.py
        apex/parallel/__init__.py
        apex/parallel/distributed.py
        apex/parallel/optimized_sync_batchnorm.py
        apex/parallel/optimized_sync_batchnorm_kernel.py
        apex/parallel/sync_batchnorm.py
        apex/pyprof/FAQs.md
        apex/pyprof/README.md
        apex/pyprof/__init__.py
        apex/pyprof/examples/.gitignore
        apex/pyprof/examples/apex/README.md
        apex/pyprof/examples/apex/fused_adam.py
        apex/pyprof/examples/apex/fused_layer_norm.py
        apex/pyprof/examples/apex/test.sh
        apex/pyprof/examples/custom_func_module/README.md
        apex/pyprof/examples/custom_func_module/custom_function.py
        apex/pyprof/examples/custom_func_module/custom_module.py
        apex/pyprof/examples/custom_func_module/test.sh
        apex/pyprof/examples/imagenet/imagenet.py
        apex/pyprof/examples/imagenet/test.sh
        apex/pyprof/examples/jit/README.md
        apex/pyprof/examples/jit/jit_script_function.py
        apex/pyprof/examples/jit/jit_script_method.py
        apex/pyprof/examples/jit/jit_trace_function.py
        apex/pyprof/examples/jit/jit_trace_method.py
        apex/pyprof/examples/jit/test.sh
        apex/pyprof/examples/lenet.py
        apex/pyprof/examples/operators.py
        apex/pyprof/examples/simple.py
        apex/pyprof/examples/user_annotation/README.md
        apex/pyprof/examples/user_annotation/resnet.py
        apex/pyprof/examples/user_annotation/test.sh
        apex/pyprof/nvtx/__init__.py
        apex/pyprof/nvtx/nvmarker.py
        apex/pyprof/parse/__main__.py
        apex/pyprof/parse/db.py
        apex/pyprof/parse/kernel.py
        apex/pyprof/parse/nvvp.py
        apex/pyprof/parse/parse.py
        apex/pyprof/prof/__init__.py
        apex/pyprof/prof/__main__.py
        apex/pyprof/prof/activation.py
        apex/pyprof/prof/base.py
        apex/pyprof/prof/blas.py
        apex/pyprof/prof/conv.py
        apex/pyprof/prof/convert.py
        apex/pyprof/prof/data.py
        apex/pyprof/prof/dropout.py
        apex/pyprof/prof/embedding.py
        apex/pyprof/prof/index_slice_join_mutate.py
        apex/pyprof/prof/linear.py
        apex/pyprof/prof/loss.py
        apex/pyprof/prof/misc.py
        apex/pyprof/prof/normalization.py
        apex/pyprof/prof/optim.py
        apex/pyprof/prof/output.py
        apex/pyprof/prof/pointwise.py
        apex/pyprof/prof/pooling.py
        apex/pyprof/prof/prof.py
        apex/pyprof/prof/randomSample.py
        apex/pyprof/prof/recurrentCell.py
        apex/pyprof/prof/reduction.py
        apex/pyprof/prof/softmax.py
        apex/pyprof/prof/usage.py
        apex/pyprof/prof/utility.py
        csrc/amp_C_frontend.cpp
        csrc/compat.h
        csrc/layer_norm_cuda.cpp
        csrc/layer_norm_cuda_kernel.cu
        csrc/mlp.cpp
        csrc/mlp_cuda.cu
        csrc/multi_tensor_adagrad.cu
        csrc/multi_tensor_adam.cu
        csrc/multi_tensor_apply.cuh
        csrc/multi_tensor_axpby_kernel.cu
        csrc/multi_tensor_l2norm_kernel.cu
        csrc/multi_tensor_lamb.cu
        csrc/multi_tensor_lamb_stage_1.cu
        csrc/multi_tensor_lamb_stage_2.cu
        csrc/multi_tensor_novograd.cu
        csrc/multi_tensor_scale_kernel.cu
        csrc/multi_tensor_sgd_kernel.cu
        csrc/syncbn.cpp
        csrc/type_shim.h
        csrc/welford.cu
        docs/source/advanced.rst
        docs/source/amp.rst
        docs/source/index.rst
        docs/source/optimizers.rst
        examples/dcgan/README.md
        examples/dcgan/main_amp.py
        examples/docker/Dockerfile
        examples/docker/README.md
        examples/imagenet/README.md
        examples/imagenet/main_amp.py
        requirements.txt
        requirements_dev.txt
        setup.py
        tests/L0/run_amp/test_add_param_group.py
        tests/L0/run_amp/test_basic_casts.py
        tests/L0/run_amp/test_checkpointing.py
        tests/L0/run_amp/test_fused_sgd.py
        tests/L0/run_amp/test_larc.py
        tests/L0/run_amp/test_multi_tensor_axpby.py
        tests/L0/run_amp/test_multi_tensor_l2norm.py
        tests/L0/run_fused_layer_norm/test_fused_layer_norm.py
        tests/L0/run_mlp/test_mlp.py
        tests/L0/run_optimizers/test_adagrad.py
        tests/L0/run_optimizers/test_adam.py
        tests/L0/run_optimizers/test_lamb.py
        tests/L0/run_pyprof_data/test_pyprof_data.py
        tests/L0/run_pyprof_nvtx/__init__.py
        tests/L0/run_pyprof_nvtx/test_pyprof_nvtx.py
        tests/L0/run_test.py
        tests/L1/cross_product/run.sh
        tests/distributed/DDP/ddp_race_condition_test.py
        tests/distributed/synced_batchnorm/python_single_gpu_unit_test.py
        tests/distributed/synced_batchnorm/single_gpu_unit_test.py
        tests/distributed/synced_batchnorm/test_batchnorm1d.py
        tests/distributed/synced_batchnorm/two_gpu_test_different_batch_size.py
        tests/distributed/synced_batchnorm/two_gpu_unit_test.py
        tests/distributed/synced_batchnorm/unit_test.sh
        tests/docker_extension_builds/run.sh
Please, commit your changes or stash them before you can switch branches.
Aborting




这个是什么原因？方便解答一下吗？




| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月19日 16:41，pengsida<notifications@github.com> 写道：

这是coco ap metric。

**Comment by pengsida** [comment]
`error: Your local changes to the following files would be overwritten by checkout`.
你可能改过apex。

**Comment by qq414256215** [comment]
我啥也没动啊，全部都是按照上面的步骤一步一步来的？咋办呀，大佬


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月19日 22:15，pengsida<notifications@github.com> 写道：

error: Your local changes to the following files would be overwritten by checkout.
你可能改过apex。

**Comment by pengsida** [comment]
建议检查一下自己的操作。

**Comment by qq414256215** [comment]
请问一下pytorch1.1.0好像没有gpu版本的，为啥这个项目建议使用torch1.1.0呢？


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月19日 22:38，pengsida<notifications@github.com> 写道：

建议检查一下自己的操作。

**Comment by pengsida** [comment]
pytorch 1.1.0有gpu版本。

**Comment by qq414256215** [comment]
可以不用安装torchvision吧？


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月20日 19:44，pengsida<notifications@github.com> 写道：

pytorch 1.1.0有gpu版本。

**Comment by qq414256215** [comment]
你好，请问一下在运行run.py
报错：         RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM


是什么原因？


| |
袁建野
|
|
aku_cintapadamu@163.com
|
签名由网易邮箱大师定制
在2020年7月22日 10:53，pengsida<notifications@github.com> 写道：

Closed #64.

**Comment by pengsida** [comment]
请列出完整报错信息。
