### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 756.00 MiB

### ISSUE THREAD

**Issue by zhenghan408** [zju3dv/snake#65]
请问用的是什么显卡呢，我rtx2080super跑不动呀，一直出错

batch_size改为1了也会报错

**Comment by pengsida** [comment]
你跑哪个命令。
我用的TiTan Xp。

**Comment by zhenghan408** [comment]
我跑的是：python train_net.py --cfg_file configs/kins_snake.yaml model kins_snake，作为训练命令

**Comment by pengsida** [comment]
把yaml文件里的batch_size减小。
