### ISSUE TITLE
def prepare_evolution() 疑问

### ISSUE THREAD

**Issue by JohnleeHIT** [zju3dv/snake#67]
![图片](https://user-images.githubusercontent.com/28437074/87897463-fd713900-ca7d-11ea-9d04-49f240215a53.png)
首先感谢作者分享如此优秀的成果，看了您的论文受益匪浅！看了您的代码，有些问题没搞懂，忘不吝赐教。
（1）文中提到对GT同样采样128个点，但代码中为何先采样128*len(poly)个点呢？
（2）此处的poly是否就是一个实例的多边形点集？如果是的话len(poly)应该为1？
（3）为什么会有can_gt_poly和can_init_poly两个量，看了下就是采样点坐标点分别减去其中最小的坐标值。

谢谢！

**Comment by pengsida** [comment]
1. 过采样边缘上的点，才能使得点在边缘上分布均匀。
2. poly是多边形点集，len(poly)是多边形点的数量。
3. `can_gt_poly`没有用到，`can_init_poly`在训练时输入到网络中得到extreme points或最终的polygon。

**Comment by JohnleeHIT** [comment]
> 
> 
>     1. 过采样边缘上的点，才能使得点在边缘上分布均匀。
> 
>     2. poly是多边形点集，len(poly)是多边形点的数量。
> 
>     3. `can_gt_poly`没有用到，`can_init_poly`在训练时输入到网络中得到extreme points或最终的polygon。

多谢回复，前两点了解了，关于第三点，论文中说到“Since the deformation should not be affected by the translation of the contour in the image, we subtract each dimension of xi by the minimum value over all vertices.” 这个应该就是can_init_poly是吧？但为什么这样就能保证轮廓变形的平移不变？

**Comment by pengsida** [comment]
这样做把坐标点归一化到原点，能减小translation的影响。

**Comment by JohnleeHIT** [comment]
> 
> 
> 这样做把坐标点归一化到原点，能减小translation的影响。

好的，谢谢！
