### ISSUE TITLE
network 功能

### ISSUE THREAD

**Issue by zhn-svg** [zju3dv/snake#68]
大神您好！麻烦问一下network里边  ct_rcnn,rcnn_snake,snake分别是做什么的网络，没有注释看不太懂。谢谢

**Comment by pengsida** [comment]
snake是论文里说的detection加snake的网络。
ct_rcnn是multi-component detection的网络。
rcnn_snake是multi-component detection加snake的网络。

**Comment by zhn-svg** [comment]
明白了，谢谢

**Comment by zhn-svg** [comment]
大神再请教一下，multi-component detection中，带component boxes的数据集是您自己标注的还是用的开源的数据集。不是很清楚multi-component的gt bounding box怎么获得的。谢谢！

**Comment by zhn-svg** [comment]
@pengsida

**Comment by pengsida** [comment]
在instance segmentation的任务中，物体轮廓一般是用polygon存的。如果是分段物体，就有多段polygon，每段polygon可以算出一个bounding box。

**Comment by twmht** [comment]
@pengsida 

請教一下，因為遮擋情況幾乎很常出現，理論上應該都是要用 multi-component 的架構吧? 但我看除了 cityscape 之外的 dataset 妳都是用 snake，而不是用 rcnn-snake，請問具體原因是什麼?

**Comment by pengsida** [comment]
因为在其他数据集上我发现这个对performance影响不是很大。
