### ISSUE TITLE
请问目标多边形的初始边界是如何得到的？

### ISSUE THREAD

**Issue by zhangjuxtu** [zju3dv/snake#69]
您好，非常感谢您的分享，从代码中收获很多。
对于目标多边形的初始边界有些疑问：
代码种dla网络预测的结果为：output['ct_hm']与output['wh']。在decode_detection函数中，由snake_decode.decode_ct_hm得到目标的ct和[bboxes, scores, clses]。从这里看，从dla网络中得的信息只有ct和[bboxes, scores, clses]。
在init_poly函数中，是由init['i_it_4py']来得到边界点的feature。而nit['i_it_4py']在snake_gcn_utils.prepare_training函数中由batch['i_it_4py']得到。
我理解的batch中的信息为从数据集标注信息得到的。为什么batch中的信息回用来作为snake网络的输入？
可能我哪里没看懂，能否帮我理解下？

**Comment by pengsida** [comment]
在训练的时候，我们用batch中的信息作为输入，包括gt bounding box和gt octagon。

**Comment by zhangjuxtu** [comment]
> 在训练的时候，我们用batch中的信息作为输入，包括gt bounding box和gt octagon。

我的理解是gt bounding box和gt octagon代表ground truth，是计算loss的时候用的。但对于预测目标的初始边界应该由预测的特征点得到呀

**Comment by zhangjuxtu** [comment]
> 训练的时候，预测目标的初始边界用的是gt。

好的，非常感谢，我再学习学习

**Comment by zhangjuxtu** [comment]
你好，基于你们snake的想法，我用到了其它地方，我的代码框架已经写完。第一次做CNN的工作，能否跟你合作下，把我的工作进一步完善？主要看我的实现哪里不合理，哪里需要改进。我的代码也是基于你们代码的结构，应该不会占用你太多时间。
如果方便的话请用这个邮箱联系我一下：zhangjunhbxf@163.com。谢谢！

**Comment by pengsida** [comment]
你可以发邮件给我，我们可以邮件里讨论你的实现方式。

**Comment by zhangjuxtu** [comment]
明白了，github也可以发邮件。
我是有你们snake的方法去做车道线检测：1. 通过heatmap检测出车道线的起始点，2.通过起始点得到车道线初始轮廓，然后用snake的方法得到检测的车道线。
从你们的工程学习到很多，非常感谢！
我把你加到我人github工程里面，请帮我看看，那些地方需要改进。





--

Best regards，

J. Zhang




在 2020-08-02 10:19:22，"pengsida" <notifications@github.com> 写道：

你可以发邮件给我，我们可以邮件里讨论你的实现方式。

**Comment by zhangjuxtu** [comment]
github: https://github.com/zhangjuxtu/snake-lane.git













--

Best regards，

J. Zhang




在 2020-08-02 10:19:22，"pengsida" <notifications@github.com> 写道：

你可以发邮件给我，我们可以邮件里讨论你的实现方式。
