### ISSUE TITLE
How is the circular convolution implemented?

### ISSUE THREAD

**Issue by LetsGoFir** [zju3dv/snake#7]
The backbone is some 'CirConv's in your paper, that is
![image](https://user-images.githubusercontent.com/59643844/74497601-1c8cfd00-4f19-11ea-9260-6f012aeee67b.png)
Then what is the f_N mean? Is it the whole feature and the (f_N)i means the feature of a pixel, which is a vertice?
Could you explain more about your circular convolution implementation, thanks!!

**Comment by pengsida** [comment]
Circular convolution:

```
class CircConv(nn.Module):
    def __init__(self, state_dim, out_state_dim=None, n_adj=4):
        super(CircConv, self).__init__()

        self.n_adj = n_adj
        out_state_dim = state_dim if out_state_dim is None else out_state_dim
        self.fc = nn.Conv1d(state_dim, out_state_dim, kernel_size=self.n_adj*2+1)

    def forward(self, input, adj):
        input = torch.cat([input[..., -self.n_adj:], input, input[..., :self.n_adj]], dim=2)
        return self.fc(input)
```

**Comment by LetsGoFir** [comment]
Sorry I find that I open 2 same issues.
