### ISSUE TITLE
Question about training my own dataset 关于训练自己数据集的一些小疑问

### ISSUE THREAD

**Issue by Ivan-Fan** [zju3dv/snake#70]
作者您好，非常感谢能开源这么优秀的代码。我在训练自己的数据集，将数据集转换成COCO格式后仿照了 #32 的方法进行训练，训练过程中报错，报错如下：
``` 
Traceback (most recent call last):
  File "train_net.py", line 54, in <module>
    main()
  File "train_net.py", line 50, in main
    train(cfg, network)
  File "train_net.py", line 32, in train
    trainer.val(epoch, val_loader, evaluator, recorder)
  File "/home/ivan/A project/snake-master/lib/train/trainers/trainer.py", line 98, in val
    result = evaluator.summarize()
  File "lib/evaluators/coco/snake.py", line 71, in summarize
    coco_dets = self.coco.loadRes(os.path.join(self.result_dir, 'results.json'))
  File "/home/ivan/anaconda3/envs/mypytorch/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 326, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
```

打开results.json发现也是空的。。。
代码没有特别的改动，只改动了sbd_snake.yaml里的batch_size, num_workers, epoch, heads里的ct_hm(这个我改成1了，我只有一个类别，不知道这样改理解得对不对)
数据集我按照以下格式存放：
├── /path/to/data
│ ├── annotations
│ │ ├── instances_train2017.json
│ │ ├── instances_val2017.json
│ ├── train2017   #放了训练集的图片
│ ├── val2017      #放了验证集的图片

**Comment by pengsida** [comment]
这里是在测试的时候报错的，你可以用类似的命令触发报错：`python run.py --type evaluate --cfg_file snake/sbd_snake.yaml model custom_model train.dataset CocoTrain test.dataset CocoVal`.
看起来是results.json是空的原因，你可以检查一下为什么results.json是空的。

**Comment by Ivan-Fan** [comment]
@pengsida 谢谢！我一会儿就去检查一下~还想问一下自己上面的一些设置修改对嘛？比如heads里的ct_hm我改为1了（只有一个类别）

**Comment by pengsida** [comment]
是的，ct_hm对应类别数量。

**Comment by Ivan-Fan** [comment]
抱歉又打扰作者啦~我今天查找了一下测试过程中的问题，发现results.json为空的问题出在network的输出上，经过gcn之后output的detection和py两个key对应的value都为空，最后定位到下面这句代码：
`output['detection'] = output['detection'][output['detection'][... , 4] > snake_config.ct_score]`
查看了一下output['detection'][... , 4]的内容，发现数值在0.01左右，而初始的snake_config.ct_score为0.05。将ct_score改为0.01后可以正常输出了（本人比较小白，其实也不确定这个参数应该设置为多少比较合适），但是发现输出结果的AP值和AR值很奇怪，不知道训练初期出现这样的情况是不是正常的呢？
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
```

**Comment by pengsida** [comment]
ct_score是确定物体是否存在的threshold。
你可以训久一些看看结果。

**Comment by Ivan-Fan** [comment]
作者您好！前一段时间在您的指导下成功将代码训练了~最近有关注到另一个问题：代码里SBD数据集设置固定输入大小是512x512（training），而我自己的数据集图片比较小，我尝试将代码里的输入大小改成128x128进行训练，结果报错：
```
RuntimeError: The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 3
```
我猜想可能是网络设置需要数据集图片大小满足一定的条件？抱歉又打扰了:)

**Comment by pengsida** [comment]
看起来不像是图片太小的原因，看起来像是你输入的数据的维度有问题。

**Comment by FantDing** [comment]
> 抱歉又打扰作者啦~我今天查找了一下测试过程中的问题，发现results.json为空的问题出在network的输出上，经过gcn之后output的detection和py两个key对应的value都为空，最后定位到下面这句代码：
> `output['detection'] = output['detection'][output['detection'][... , 4] > snake_config.ct_score]`
> 查看了一下output['detection'][... , 4]的内容，发现数值在0.01左右，而初始的snake_config.ct_score为0.05。将ct_score改为0.01后可以正常输出了（本人比较小白，其实也不确定这个参数应该设置为多少比较合适），但是发现输出结果的AP值和AR值很奇怪，不知道训练初期出现这样的情况是不是正常的呢？
> 
> ```
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> ```

你好，我现在训练也是这种情况，怎么回事。自己标注的coco形式的数据集，类别就1类
