### ISSUE TITLE
关于demo的问题

### ISSUE THREAD

**Issue by fanwang-1** [zju3dv/snake#71]
你好，就是我在跑demo的时候，那个图片显示出来后，那个是没有边框的，感觉是可视化的原因，但是没有报错，也不知道怎么改了

**Comment by pengsida** [comment]
可以贴一下结果的图片吗，我不知道你说的“没有边框”是什么意思。

**Comment by fanwang-1** [comment]
我知道了，其实是那个图像没有被识别出来，我以为是那个我环境配错了，不好意思。谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/snake"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 下午3:19
收件人:&nbsp;"zju3dv/snake"<snake@noreply.github.com&gt;;
抄送:&nbsp;"布凡"<1730705091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/snake] 关于demo的问题 (#71)





 
可以贴一下结果的图片吗，我不知道你说的“没有边框”是什么意思。

**Comment by pengsida** [comment]
好的。

**Comment by fanwang-1** [comment]
你好，就是这个网络怎么修改训练的显卡呢？我在lib/configs/configs.py里面更改编号，没有反应，还是用0号显卡训练。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/snake"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月27日(星期一) 上午10:15
收件人:&nbsp;"zju3dv/snake"<snake@noreply.github.com&gt;;
抄送:&nbsp;"布凡"<1730705091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/snake] 关于demo的问题 (#71)





 
Closed #71.

**Comment by pengsida** [comment]
在yaml文件里面改。

**Comment by fanwang-1** [comment]
是在那个配置文件里面的
像这样吗？
#gpus: (0, 1, 2, 3, 4, 5, 6, 7)
#gpus: (1, 2)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/snake"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 下午4:24
收件人:&nbsp;"zju3dv/snake"<snake@noreply.github.com&gt;;
抄送:&nbsp;"布凡"<1730705091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/snake] 关于demo的问题 (#71)





 
在yaml文件里面改。

**Comment by pengsida** [comment]
对的，前面不要加#。

**Comment by fanwang-1** [comment]
RuntimeError: CUDA out of memory. Tried to allocate 1.27 GiB (GPU 0; 11.17 GiB total capacity; 9.60 GiB already allocated; 942.56 MiB free; 234.12 MiB cached) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:267)

我改后他还是在 GPU0上跑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/snake"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 下午5:08
收件人:&nbsp;"zju3dv/snake"<snake@noreply.github.com&gt;;
抄送:&nbsp;"布凡"<1730705091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/snake] 关于demo的问题 (#71)





 
对的，前面不要加#。

**Comment by fanwang-1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/snake"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 下午5:08
收件人:&nbsp;"zju3dv/snake"<snake@noreply.github.com&gt;;
抄送:&nbsp;"布凡"<1730705091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/snake] 关于demo的问题 (#71)





 
对的，前面不要加#。

**Comment by fanwang-1** [comment]
那个一直显示训练的时候内存不够，现在是我想训练自己的数据，但是就是一直困住在这里



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pengsida"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午5:08
收件人: "zju3dv/snake"<snake@noreply.github.com&gt;; 
抄送: "布凡"<1730705091@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zju3dv/snake] 关于demo的问题 (#71)





 
对的，前面不要加#。

**Comment by pengsida** [comment]
你修改的是哪个yaml文件，用的是哪个命令，yaml文件里的batch size多大？

**Comment by fanwang-1** [comment]
我修改的是coco_snake.yaml文件用的是这一条命令
python -W ignore train_net.py --cfg_file ./configs/coco_snake.yaml



我调整小了batch size然后是可以训练的，应该是batch size 太大了。


不过我个疑问，就是batch size调小了，那么训练效果不就会差一点了吗，那有没有什么办法可以调整一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pengsida"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 晚上8:24
收件人: "zju3dv/snake"<snake@noreply.github.com&gt;; 
抄送: "布凡"<1730705091@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zju3dv/snake] 关于demo的问题 (#71)





 
你修改的是哪个yaml文件，用的是哪个命令，yaml文件里的batch size多大？
