### ISSUE TITLE
The problem about DCN

### ISSUE THREAD

**Issue by u53216** [zju3dv/snake#74]
Every time I run to the DCN module, the program stops with no error, just "Process Finished with exit code-1". I tried to debug where it was wrong and found that the program went to stop at _back.dcn_v2_forward in DCN_v2_conv. My CUDA version is 9.0, and pytorch and other machines are strictly installed in accordance with the version in Install. Could you please tell me what the problem is?
![截图](https://user-images.githubusercontent.com/40450152/89603492-d6976d00-d89b-11ea-9d56-d33d0e52781a.PNG)
![截图2](https://user-images.githubusercontent.com/40450152/89603513-e616b600-d89b-11ea-8ee8-905510669502.PNG)

**Comment by u53216** [comment]
This is the log information when I compiled DCNv2. Thanks for the trouble。

**Comment by u53216** [comment]
`running build_ext
building '_ext' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/home
creating build/temp.linux-x86_64-3.7/home/hjc
creating build/temp.linux-x86_64-3.7/home/hjc/Project
creating build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake
creating build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib
creating build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc
creating build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2
creating build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src
creating build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cpu
creating build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda
gcc -pthread -B /home/hjc/anaconda3/envs/snake_new/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/TH -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/hjc/anaconda3/envs/snake_new/include/python3.7m -c /home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/vision.cpp -o build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/hjc/anaconda3/envs/snake_new/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/TH -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/hjc/anaconda3/envs/snake_new/include/python3.7m -c /home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cpu/dcn_v2_cpu.cpp -o build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cpu/dcn_v2_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-9.0/bin/nvcc -DWITH_CUDA -I/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/TH -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/hjc/anaconda3/envs/snake_new/include/python3.7m -c /home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_cuda.cu -o build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h:277:48: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
`

**Comment by u53216** [comment]
` using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
                                                ^
/usr/local/cuda-9.0/bin/nvcc -DWITH_CUDA -I/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/TH -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/hjc/anaconda3/envs/snake_new/include/python3.7m -c /home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_im2col_cuda.cu -o build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_im2col_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h:277:48: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
 using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
                                                ^
/usr/local/cuda-9.0/bin/nvcc -DWITH_CUDA -I/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/TH -I/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/hjc/anaconda3/envs/snake_new/include/python3.7m -c /home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_psroi_pooling_cuda.cu -o build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_psroi_pooling_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h:277:48: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
 using IntList C10_DEPRECATED_USING = ArrayRef<int64_t>;
                                                ^
/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_psroi_pooling_cuda.cu: In lambda function:
/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_psroi_pooling_cuda.cu:317:120: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated (declared at /home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:47) [-Wdeprecated-declarations]
   AT_DISPATCH_FLOATING_TYPES(input.type(), "dcn_v2_psroi_pooling_cuda_forward", [&] {
                                                                                                                        ^
/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_psroi_pooling_cuda.cu: In lambda function:
/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_psroi_pooling_cuda.cu:391:126: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated (declared at /home/hjc/anaconda3/envs/snake_new/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:47) [-Wdeprecated-declarations]
   AT_DISPATCH_FLOATING_TYPES(out_grad.type(), "dcn_v2_psroi_pooling_cuda_backward", [&] {
                                                                                                                              ^
creating build/lib.linux-x86_64-3.7
g++ -pthread -shared -B /home/hjc/anaconda3/envs/snake_new/compiler_compat -L/home/hjc/anaconda3/envs/snake_new/lib -Wl,-rpath=/home/hjc/anaconda3/envs/snake_new/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/vision.o build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cpu/dcn_v2_cpu.o build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_cuda.o build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_im2col_cuda.o build/temp.linux-x86_64-3.7/home/hjc/Project/deepsnake/lib/csrc/dcn_v2/src/cuda/dcn_v2_psroi_pooling_cuda.o -L/usr/local/cuda-9.0/lib64 -lcudart -o build/lib.linux-x86_64-3.7/_ext.cpython-37m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.7/_ext.cpython-37m-x86_64-linux-gnu.so ->
`

**Comment by pengsida** [comment]
I never encounter this problem.
You could ask the author of DCNv2 code: https://github.com/CharlesShang/DCNv2

**Comment by u53216** [comment]
@pengsida 准确的说是应该我一调用_ext文件中有关cuda的就不行，我DCN使用了cpu就可以使用，但extreme_utils也是这个中止的情况。在编译的时候我除了要注意CUDA版本（9.0），pytorch版本（1.1.0）还要注意什么，比如gcc版本？

**Comment by u53216** [comment]
@pengsida 就是到这个上采样的部分，调取_ext文件时如果使用cuda就会发生中断
![截图5](https://user-images.githubusercontent.com/40450152/89622840-3efb4400-d8c6-11ea-9e0f-dc3fc21d0194.PNG)

**Comment by pengsida** [comment]
你电脑能用跑其他pytorch的cuda编译的代码吗？

**Comment by u53216** [comment]
@pengsida 你指的是pytorch和cuda编译的代码吗？这我不清楚，没有尝试过，但是pytorch能在gpu上正常运行

**Comment by pengsida** [comment]
可能你的环境跑不了pytorch和cuda编译的代码。

**Comment by u53216** [comment]
@pengsida 额。。好吧那这是什么原因造成的，有什么解决办法吗

**Comment by pengsida** [comment]
你可以网上查查，我没遇到过这问题。

**Comment by u53216** [comment]
@pengsida 好的吧有无可以不用编译后代码的运行方法吗

**Comment by pengsida** [comment]
对于这个代码，是需要编译的。

**Comment by u53216** [comment]
@pengsida 好的谢谢了，实在不行我回去换一台服务器试试再学习下snake部分哈哈
