### ISSUE TITLE
训练过程的bug

### ISSUE THREAD

**Issue by DesmondSL** [zju3dv/snake#80]
图片中目标占的区域较大，训练结果很差，如下图：
![0111_A6D667_LZWADAGA8E4068251_LZW6432KF_scaled](https://user-images.githubusercontent.com/24861639/90514677-0e53be00-e194-11ea-9516-410ef50f5a85.png)

如果将该图resize到较小的尺寸，补黑边，训练结果如下：
![2020-08-18 20-48-01屏幕截图](https://user-images.githubusercontent.com/24861639/90514767-317e6d80-e194-11ea-9050-d00af9efddac.png)

网络是否有可控制的参数？谢谢。

**Comment by pengsida** [comment]
你说的可控制的参数是什么？

**Comment by DesmondSL** [comment]
训练网络发现小目标的效果比较好，比如文本。但是如该是一个充满大半个图片的目标，比如一辆车，效果很差或者基本没有结果。想知道这个问题是由于什么原因导致的，是否是在检测时将较大目标的框抑制掉了？

**Comment by pengsida** [comment]
1. 大物体的检测对于大多数detector效果都不太好，你的目标物体长宽多少。
2. 一般是做multi-scale detection。
3. 检测的时候没有抑制大物体的框。

**Comment by DesmondSL** [comment]
640×480 的图中目标大致占500×400

**Comment by pengsida** [comment]
500x400的物体不是很大，可能是你们训练数据里这种物体比较少。

**Comment by DesmondSL** [comment]
方便加个QQ详细聊一下吗？
664263346

**Comment by pengsida** [comment]
可以发邮件交流。
