### ISSUE TITLE
Segmentation Fault error

### ISSUE THREAD

**Issue by riyakothari** [zju3dv/snake#81]
Facing a segmentation fault error while using deep_snake code for my problem statement.
I have followed all the steps mentioned in the documentation, and still facing this issue.
Below is the description of the error.

![image](https://user-images.githubusercontent.com/12575490/90937617-ffe7eb00-e3bb-11ea-81f2-d0f47b3f8c81.png)

Following is the environment details.

![image](https://user-images.githubusercontent.com/12575490/90937658-1a21c900-e3bc-11ea-9527-d5d4884a1fb7.png)

**Comment by riyakothari** [comment]
I downgraded my Cuda version to 9.2 with pytorch version as 1.1.0. Still getting the same segmentation fault error.

**Comment by pengsida** [comment]
Remove previous things generated by compilation and recompile them.

**Comment by riyakothari** [comment]
I did remove the previous things generated during compilation and then only did I recompile it. The files that I removed before recompiling were the build folders and the .so files from the folders in lib/csrc, and also the apex folder (and checked it out again). Are there any other files that need to be deleted before recompiling?

**Comment by pengsida** [comment]
Maybe https://github.com/zju3dv/snake/issues/77 helps.
Did you `export CUDA_HOME="/usr/local/cuda-9.0"` before compilation?

**Comment by riyakothari** [comment]
Yeah, i did that before compilation.

**Comment by pengsida** [comment]
You could try to install pytorch with conda.
