### ISSUE TITLE
Fine-tuning on a customized dataset

### ISSUE THREAD

**Issue by tommi95** [zju3dv/snake#82]
Hi, I am trying to fine-tune a pre-trained model on a customized dataset. 
My doubts are:

1. Is it possible to modify the training protocol or, in other words, is it possible to train a pre-trained model keeping the weights of specific layers frozen and others not? 
If it is and considering the task of object segmentation in a scenario with objects placed on a table, have you investigated which layers of the model is convenient to re-train and which ones is convenient to froze during the training phase?

2. Could you kindly provide, if possible, the weights of your model (_.pth_) trained on the COCO dataset if possible?

3. Finally I am wondering if it could be possible during the training phase to load a pre-trained model but excluding only the last layer and initializing the weights of a new final layer in a randomic way for example?

Thank you for your attention and your work!

**Comment by pengsida** [comment]
1. You can keep the weights of specific layers frozen. I did not investigate such things.
2. I cannot find the concrete code and model on COCO. The networks are trained on remote servers, which have been closed.
3. Yes, you can load the a pre-trained model excluding the last layer. But currently the code does not provide the functionality.

**Comment by tommi95** [comment]
So if I understood correctly I could do points 1 and 3 but for both the code has not been implemented yet.
Could you kindly indicate which python functions should I modify?
Thank you!

**Comment by pengsida** [comment]
`load_model`: https://github.com/zju3dv/snake/blob/master/lib/utils/net_utils.py#L285
`load_network`: https://github.com/zju3dv/snake/blob/master/lib/utils/net_utils.py#L327

**Comment by tommi95** [comment]
Thank you for all your answers!

**Comment by tommi95** [comment]
Hi, have you also considered in your code the case in which no object is detected in the image?
Because in my case, while processing the custom dataset, more specifically in the forward step of the cp_head.py function, the variable named _roi_ is sometimes empty and in this case the code terminates with an error (CUDNN_STATUS_BAD_PARAM).
Thank you in advance!

**Comment by pengsida** [comment]
No, I did not handle this case.

**Comment by tommi95** [comment]
Ok, thank you again also for your quick replies!

**Comment by tommi95** [comment]
I have another question: is the ct_score variable used in the training phase or it is used only in the testing one?
Thank you!

**Comment by pengsida** [comment]
`ct_score` is used only in the testing.

**Comment by tommi95** [comment]
Sorry I have another question please: 
is the Deepsnake segmenter class-agnostic, isn' t it?

**Comment by pengsida** [comment]
It is class-agnostic.

**Comment by tommi95** [comment]
Ok, thank you very much again!

**Comment by TzzLongwind** [comment]
@tommi95 

> Hi, have you also considered in your code the case in which no object is detected in the image? Because in my case, while processing the custom dataset, more specifically in the forward step of the cp_head.py function, the variable named _roi_ is sometimes empty and in this case the code terminates with an error (CUDNN_STATUS_BAD_PARAM). Thank you in advance!

I have encountered the same problem recently. Have you solved it? Can you share the solution? Thank you.
