### ISSUE TITLE
I meet an Error when I run the run.py, could you help me? 在运行run.py的时候我遇到了一个问题，能帮我看一下吗？

### ISSUE THREAD

**Issue by JimXu1989** [zju3dv/snake#83]
在运行这行的时候：
from lib.csrc.dcn_v2 import _ext as _backend

我遇到了这个错误：
ImportError: cannot import name '_ext' from 'lib.csrc.dcn_v2'

_ext是什么呢？我没有找到。

when I excute the following code:
from lib.csrc.dcn_v2 import _ext as _backend

I met this error:
ImportError: cannot import name '_ext' from 'lib.csrc.dcn_v2'

**Comment by fornote** [comment]
Hi @pengsida , I have the same problem.

**Comment by fornote** [comment]
INSTALL.md may help you.

**Comment by pengsida** [comment]
需要先编译代码。
