### ISSUE TITLE
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.

### ISSUE THREAD

**Issue by fornote** [zju3dv/snake#85]
hello,
     Thanks for your so great work. While I run `python train_net.py --cfg_file configs/sbd_snake.yaml model sbd_snake` to trainning, there is an error.
    ` /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.` keeps repeating.

**Comment by pengsida** [comment]
Use pytorch 1.1.

**Comment by fornote** [comment]
> Use pytorch 1.1.

thank you, I will have a try.

**Comment by pengsida** [comment]
You could revise the corresponding code.

**Comment by hande6688** [comment]
可以使用torch1.4.0+cuda10.1
然后加
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
