### ISSUE TITLE
训练epoch=400，运行到epoch=135就不打印训练日志了，GPU一直处于3%，这是我那里设置有问题吗？

### ISSUE THREAD

**Issue by hande6688** [zju3dv/snake#88]
eta: 0:00:59  epoch: 135  step: 91860  ct_loss: 0.2399  wh_loss: 1.1110  ex_loss: 1.1599  py_loss: 1.8119  loss: 3.3228  data: 0.0043  batch: 0.7725  lr: 0.000005  max_mem: 5846
eta: 0:00:43  epoch: 135  step: 91880  ct_loss: 0.1979  wh_loss: 0.8857  ex_loss: 1.0762  py_loss: 1.4782  loss: 2.8408  data: 0.0043  batch: 0.7780  lr: 0.000005  max_mem: 5846
eta: 0:00:28  epoch: 135  step: 91900  ct_loss: 0.2463  wh_loss: 1.0269  ex_loss: 1.1554  py_loss: 1.6829  loss: 3.1873  data: 0.0044  batch: 0.7241  lr: 0.000005  max_mem: 5846
eta: 0:00:12  epoch: 135  step: 91920  ct_loss: 0.1469  wh_loss: 0.6536  ex_loss: 1.1515  py_loss: 1.3708  loss: 2.7346  data: 0.0045  batch: 0.7189  lr: 0.000005  max_mem: 5846
eta: 0:00:00  epoch: 135  step: 91935  ct_loss: 0.1809  wh_loss: 0.8144  ex_loss: 1.1794  py_loss: 1.3634  loss: 2.8051  data: 0.0047  batch: 0.7535  lr: 0.000005  max_mem: 5846

**Comment by pengsida** [comment]
我没遇到过这个问题，不知道具体原因。

**Comment by hande6688** [comment]
![image](https://user-images.githubusercontent.com/29244715/92930242-6371af80-f474-11ea-9110-7e6a7d2bff1a.png)
训练成这样子，可以判断是数据原因还是什么原因呢
@pengsida

**Comment by pengsida** [comment]
没看过你的数据，我不知道具体原因。
应该是数据的原因。
