### ISSUE TITLE
How to train a new model with supervisely person dataset

### ISSUE THREAD

**Issue by rose-jinyang** [zju3dv/snake#89]
Hello
How are you?
Thanks for contributing this project.
I am going to train a new model for human segmentation with supervisely person dataset.
https://github.com/nicehuster/mmdetection-supervisely-person-datasets
How can I train a new model with this dataset?
Thanks

**Comment by pengsida** [comment]
1. Convert the dataset into the coco format.
2. Add a dataset in `lib/datasets/dataset_catalog.py` or use one of the existing datasets.

**Comment by rose-jinyang** [comment]
Hi
Thanks for your reply.
One more question.
Can I train ONLY human with COCO 2017 dataset?
Thanks

**Comment by pengsida** [comment]
Sorry, I forgot to reply the message after reading it.
You can achieve this by filtering the coco annotations.

**Comment by zhuzhenkun666** [comment]
Hello, I want ask where to filter the coco annotations?

**Comment by pengsida** [comment]
This line: https://github.com/zju3dv/snake/blob/master/lib/datasets/coco/snake.py#L21

**Comment by zhuzhenkun666** [comment]
OK,thanks
