### ISSUE TITLE
关于Initial contour proposal的问题

### ISSUE THREAD

**Issue by Dawn-LX** [zju3dv/snake#9]
您好！
我认真阅读了您的论文，但是有些疑惑
section 3.2 Initial contour proposal.
“the diamond contour is uniformly upsampled to 40 points, and deep snake correspondingly outputs 40 offsets.”

为什么要对菱形轮廓采40个样？ 后面的loss function 不是只用到了4个点吗？能否解答一下，感激不尽！谢谢！

**Comment by pengsida** [comment]
如果有40个点，网络的输入信息更丰富，好做预测。

**Comment by Dawn-LX** [comment]
> 如果有40个点，网络的输入信息更丰富，好做预测。

好的谢谢！
