### ISSUE TITLE
About network extraction features

### ISSUE THREAD

**Issue by tyyisbest** [zju3dv/snake#91]
Solving the offset of the vertex results in that both the initial contour and the deformation of the contour in the second step are input into the same network. I am not quite sure how to get these two different results.

**Comment by pengsida** [comment]
They are processed by different networks.

**Comment by tyyisbest** [comment]
Thanks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/snake"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 中午11:56
收件人:&nbsp;"zju3dv/snake"<snake@noreply.github.com&gt;;
抄送:&nbsp;"Halo."<407885173@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/snake] About network extraction features (#91)





 
They are processed by different networks.
