### ISSUE TITLE
Why not choose FCOS as the detector?

### ISSUE THREAD

**Issue by neiheih** [zju3dv/snake#95]
Many SOTA instance segmentation methods choose FCOS as detector, such as blendmask, polarmask, centermask.
Have ever thought about snake with FCOS as detector or conducted some experiments about this?

**Comment by pengsida** [comment]
I did not conduct related experiments.

**Comment by XdpAreKid** [comment]
I think ExtremeNet maybe better choice.But the detector what you choose is not important in this Method.
