### ISSUE TITLE
If the predicted coordinates beyond boundary, how it gets the related vectors from cnn_feature?

### ISSUE THREAD

**Issue by fornote** [zju3dv/snake#96]
Hello, thanks for your great job,I have a question as mentioned in the title. From the code, I haven't found the process for this situation.

If `feature = torch.nn.functional.grid_sample()` is the process for this case?

**Comment by pengsida** [comment]
I did not understand what you meant.

**Comment by fornote** [comment]
For example, one predicted counter point's coordinate is (513, 513),while the image size is(512,512). I want to know at next Snake stage, how to get the vector corresponding to coordinates.

**Comment by pengsida** [comment]
I clip the coordinates outside the image. So, the situation you talk about won't happen.
