### ISSUE TITLE
想要替换Centernet 的 CNN backbone

### ISSUE THREAD

**Issue by Ruanyuzhe** [zju3dv/snake#97]
作者你好，非常感谢您的代码，我最近想要把您的网络应用于医疗数据集中去，但是效果并不理想，想稍稍修改一下网络构架，我看论文里说Centernet用的是CNNbackbone，想要将其修改，修改成Unet类型的，但代码有点没有理的太清楚，困扰了我很久，想问一下如果要修改网络架构部分，应该修改那一块代码呢

**Comment by pengsida** [comment]
这里选择使用哪个网络：https://github.com/zju3dv/snake/blob/master/lib/networks/rcnn_snake/__init__.py
