### ISSUE TITLE
Features Extraction

### ISSUE THREAD

**Issue by aswa123** [zju3dv/snake#99]
I want to extract the features after training so how do I find the exact place in this code?

**Comment by pengsida** [comment]
Here: https://github.com/zju3dv/snake/blob/master/lib/networks/rcnn_snake/ct_rcnn_snake.py#L38

**Comment by tommi95** [comment]
I figured out that the last two dimensions of the tensor _cnn_feature_ at line 38 (same is valid for the variables named _act_hm_ and _awh_ which are the outputs of the CenterNet detector) are respectively equal to 144 and 192. 
What do these numbers represent? Are they just the dimensions of the feature map needed in the computations?

**Comment by pengsida** [comment]
They are the resolution of feature maps.
I don't know what you mean by "Are they just the dimensions of the feature map needed in the computations"?

**Comment by tommi95** [comment]
Ok, thank you!
With that I meant is if these dimensions are chosen in this way for a particular reason other that for structural purposes.
So, a feature map with this dimensions is used to represent each object class (act_hm variable) and one other map is used for the height and the width of each bounding box detected from the image, is it correct?

**Comment by pengsida** [comment]
I did not choose these dimensions in purpose.
